using System;

namespace JonasTest.Core
{
	public class Academics
	{
		public int UNITID { get;set; }
		public	decimal? PCIP01			{get; set; }
		public	decimal? PCIP03			{get; set;}
		public	decimal? PCIP04			{get; set;}
		public	decimal? PCIP05			{get; set;}
		public	decimal? PCIP09			{get; set;}
		public	decimal? PCIP10			{get; set;}
		public decimal? PCIP11			{get; set;}
		public	decimal? PCIP12			{get; set;}
		public	decimal? PCIP13			{get; set;}
		public	decimal? PCIP14			{get; set;}
		public	decimal? PCIP15			{get; set;}
		public	decimal? PCIP16			{get; set;}
		public	decimal? PCIP19			{get; set;}
		public	decimal? PCIP22			{get; set;}
		public	decimal? PCIP23			{get; set;}
		public	decimal? PCIP24			{get; set;}
		public  decimal? PCIP25		{get; set;}
	    public  decimal? PCIP26		{get; set;}
	    public  decimal? PCIP27		{get; set;}
	    public  decimal? PCIP29		{get; set;}
	    public  decimal? PCIP30		{get; set;}
	    public  decimal? PCIP31		{get; set;}
	    public  decimal? PCIP38		{get; set;}
	    public  decimal? PCIP39		{get; set;}
	    public  decimal? PCIP40		{get; set;}
	    public  decimal? PCIP41		{get; set;}
	    public  decimal? PCIP42		{get; set;}
	    public  decimal? PCIP43		{get; set;}
	    public  decimal? PCIP44		{get; set;}
	    public  decimal? PCIP45		{get; set;}
	    public  decimal? PCIP46		{get; set;}
	    public  decimal? PCIP47		{get; set;}
	    public  decimal? PCIP48		{get; set;}
	    public  decimal? PCIP49		{get; set;}
	    public  decimal? PCIP50		{get; set;}
	    public  decimal? PCIP51		{get; set;}
	    public  decimal? PCIP52		{get; set;}
	    public  decimal? PCIP54		{get; set;}
	    public  int?	 CIP01CERT1  {get; set;}
	    public  int?	 CIP01CERT2  {get; set;}
	    public  int?	 CIP01ASSOC  {get; set;}
	    public  int?	 CIP01CERT4  {get; set;}
	    public  int?	 CIP01BACHL  {get; set;}
	    public  int?	 CIP03CERT1  {get; set;}
	    public  int?	 CIP03CERT2  {get; set;}
	    public  int?	 CIP03ASSOC  {get; set;}
	    public  int?	 CIP03CERT4  {get; set;}
	    public  int?	 CIP03BACHL  {get; set;}
	    public  int?	 CIP04CERT1  {get; set;}
	    public  int?	 CIP04CERT2  {get; set;}
	    public  int?	 CIP04ASSOC  {get; set;}
	    public  int?	 CIP04CERT4  {get; set;}
	    public  int?	 CIP04BACHL  {get; set;}
	    public  int?	 CIP05CERT1  {get; set;}
	    public  int?	 CIP05CERT2  {get; set;}
	    public  int?	 CIP05ASSOC  {get; set;}
	    public  int?	 CIP05CERT4  {get; set;}
	    public  int?	 CIP05BACHL  {get; set;}
	    public  int?	 CIP09CERT1  {get; set;}
	    public  int?	 CIP09CERT2  {get; set;}
	    public  int?	 CIP09ASSOC  {get; set;}
	    public  int?	 CIP09CERT4  {get; set;}
	    public  int?	 CIP09BACHL  {get; set;}
	    public  int?	 CIP10CERT1  {get; set;}
	    public  int?	 CIP10CERT2  {get; set;}
	    public  int?	 CIP10ASSOC  {get; set;}
	    public  int?	 CIP10CERT4  {get; set;}
	    public  int?	 CIP10BACHL  {get; set;}
	    public  int?	 CIP11CERT1  {get; set;}
	    public  int?	 CIP11CERT2  {get; set;}
	    public  int?	 CIP11ASSOC  {get; set;}
	    public  int?	 CIP11CERT4  {get; set;}
	    public  int?	 CIP11BACHL  {get; set;}
	    public  int?	 CIP12CERT1  {get; set;}
	    public  int?	 CIP12CERT2  {get; set;}
	    public  int?	 CIP12ASSOC  {get; set;}
	    public  int?	 CIP12CERT4  {get; set;}
	    public  int?	 CIP12BACHL  {get; set;}
	    public  int?	 CIP13CERT1  {get; set;}
	    public  int?	 CIP13CERT2  {get; set;}
	    public  int?	 CIP13ASSOC  {get; set;}
	    public  int?	 CIP13CERT4  {get; set;}
	    public  int?	 CIP13BACHL  {get; set;}
	    public  int?	 CIP14CERT1  {get; set;}
	    public  int?	 CIP14CERT2  {get; set;}
	    public  int?	 CIP14ASSOC  {get; set;}
	    public  int?	 CIP14CERT4  {get; set;}
	    public  int?	 CIP14BACHL  {get; set;}
	    public  int?	 CIP15CERT1  {get; set;}
	    public  int?	 CIP15CERT2  {get; set;}
	    public  int?	 CIP15ASSOC  {get; set;}
	    public  int?	 CIP15CERT4  {get; set;}
	    public  int?	 CIP15BACHL  {get; set;}
	    public  int?	 CIP16CERT1  {get; set;}
	    public  int?	 CIP16CERT2  {get; set;}
	    public  int?	 CIP16ASSOC  {get; set;}
	    public  int?	 CIP16CERT4  {get; set;}
	    public  int?	 CIP16BACHL  {get; set;}
	    public  int?	 CIP19CERT1  {get; set;}
	    public  int?	 CIP19CERT2  {get; set;}
	    public  int?	 CIP19ASSOC  {get; set;}
	    public  int?	 CIP19CERT4  {get; set;}
	    public  int?	 CIP19BACHL  {get; set;}
	    public  int?	 CIP22CERT1  {get; set;}
	    public  int?	 CIP22CERT2  {get; set;}
	    public  int?	 CIP22ASSOC  {get; set;}
	    public  int?	 CIP22CERT4  {get; set;}
	    public  int?	 CIP22BACHL  {get; set;}
	    public  int?	 CIP23CERT1  {get; set;}
	    public  int?	 CIP23CERT2  {get; set;}
	    public  int?	 CIP23ASSOC  {get; set;}
	    public  int?	 CIP23CERT4  {get; set;}
	    public  int?	 CIP23BACHL  {get; set;}
	    public  int?	 CIP24CERT1  {get; set;}
	    public  int?	 CIP24CERT2  {get; set;}
	    public  int?	 CIP24ASSOC  {get; set;}
	    public  int?	 CIP24CERT4  {get; set;}
	    public  int?	 CIP24BACHL  {get; set;}
	    public  int?	 CIP25CERT1  {get; set;}
	    public  int?	 CIP25CERT2  {get; set;}
	    public  int?	 CIP25ASSOC  {get; set;}
	    public  int?	 CIP25CERT4  {get; set;}
	    public  int?	 CIP25BACHL  {get; set;}
	    public  int?	 CIP26CERT1  {get; set;}
	    public  int?	 CIP26CERT2  {get; set;}
	    public  int?	 CIP26ASSOC  {get; set;}
	    public  int?	 CIP26CERT4  {get; set;}
	    public  int?	 CIP26BACHL  {get; set;}
	    public  int?	 CIP27CERT1  {get; set;}
	    public  int?	 CIP27CERT2  {get; set;}
	    public  int?	 CIP27ASSOC  {get; set;}
	    public  int?	 CIP27CERT4  {get; set;}
	    public  int?	 CIP27BACHL  {get; set;}
	    public  int?	 CIP29CERT1  {get; set;}
	    public  int?	 CIP29CERT2  {get; set;}
	    public  int?	 CIP29ASSOC  {get; set;}
	    public  int?	 CIP29CERT4  {get; set;}
	    public  int?	 CIP29BACHL  {get; set;}
	    public  int?	 CIP30CERT1  {get; set;}
	    public  int?	 CIP30CERT2  {get; set;}
	    public  int?	 CIP30ASSOC  {get; set;}
	    public  int?	 CIP30CERT4  {get; set;}
	    public  int?	 CIP30BACHL  {get; set;}
	    public  int?	 CIP31CERT1  {get; set;}
	    public  int?	 CIP31CERT2  {get; set;}
	    public  int?	 CIP31ASSOC  {get; set;}
	    public  int?	 CIP31CERT4  {get; set;}
	    public  int?	 CIP31BACHL  {get; set;}
	    public  int?	 CIP38CERT1  {get; set;}
	    public  int?	 CIP38CERT2  {get; set;}
	    public  int?	 CIP38ASSOC  {get; set;}
	    public  int?	 CIP38CERT4  {get; set;}
	    public  int?	 CIP38BACHL  {get; set;}
	    public  int?	 CIP39CERT1  {get; set;}
	    public  int?	 CIP39CERT2  {get; set;}
	    public  int?	 CIP39ASSOC  {get; set;}
	    public  int?	 CIP39CERT4  {get; set;}
	    public  int?	 CIP39BACHL  {get; set;}
	    public  int?	 CIP40CERT1  {get; set;}
	    public  int?	 CIP40CERT2  {get; set;}
	    public  int?	 CIP40ASSOC  {get; set;}
	    public  int?	 CIP40CERT4  {get; set;}
	    public  int?	 CIP40BACHL  {get; set;}
	    public  int?	 CIP41CERT1  {get; set;}
	    public  int?	 CIP41CERT2  {get; set;}
	    public  int?	 CIP41ASSOC  {get; set;}
	    public  int?	 CIP41CERT4  {get; set;}
	    public  int?	 CIP41BACHL  {get; set;}
	    public  int?	 CIP42CERT1  {get; set;}
	    public  int?	 CIP42CERT2  {get; set;}
	    public  int?	 CIP42ASSOC  {get; set;}
	    public  int?	 CIP42CERT4  {get; set;}
	    public  int?	 CIP42BACHL  {get; set;}
	    public  int?	 CIP43CERT1  {get; set;}
	    public  int?	 CIP43CERT2  {get; set;}
	    public  int?	 CIP43ASSOC  {get; set;}
	    public  int?	 CIP43CERT4  {get; set;}
	    public  int?	 CIP43BACHL  {get; set;}
	    public  int?	 CIP44CERT1  {get; set;}
	    public  int?	 CIP44CERT2  {get; set;}
	    public  int?	 CIP44ASSOC  {get; set;}
	    public  int?	 CIP44CERT4  {get; set;}
	    public  int?	 CIP44BACHL  {get; set;}
	    public  int?	 CIP45CERT1  {get; set;}
	    public  int?	 CIP45CERT2  {get; set;}
	    public  int?	 CIP45ASSOC  {get; set;}
	    public  int?	 CIP45CERT4  {get; set;}
	    public  int?	 CIP45BACHL  {get; set;}
	    public  int?	 CIP46CERT1  {get; set;}
	    public  int?	 CIP46CERT2  {get; set;}
	    public  int?	 CIP46ASSOC  {get; set;}
	    public  int?	 CIP46CERT4  {get; set;}
	    public  int?	 CIP46BACHL  {get; set;}
	    public  int?	 CIP47CERT1  {get; set;}
	    public  int?	 CIP47CERT2  {get; set;}
	    public  int?	 CIP47ASSOC  {get; set;}
	    public  int?	 CIP47CERT4  {get; set;}
	    public  int?	 CIP47BACHL  {get; set;}
	    public  int?	 CIP48CERT1  {get; set;}
	    public  int?	 CIP48CERT2  {get; set;}
	    public  int?	 CIP48ASSOC  {get; set;}
	    public  int?	 CIP48CERT4  {get; set;}
	    public  int?	 CIP48BACHL  {get; set;}
	    public  int?	 CIP49CERT1  {get; set;}
	    public  int?	 CIP49CERT2  {get; set;}
	    public  int?	 CIP49ASSOC  {get; set;}
	    public  int?	 CIP49CERT4  {get; set;}
	    public  int?	 CIP49BACHL  {get; set;}
	    public  int?	 CIP50CERT1  {get; set;}
	    public  int?	 CIP50CERT2  {get; set;}
	    public  int?	 CIP50ASSOC  {get; set;}
	    public  int?	 CIP50CERT4  {get; set;}
	    public  int?	 CIP50BACHL  {get; set;}
	    public  int?	 CIP51CERT1  {get; set;}
	    public  int?	 CIP51CERT2  {get; set;}
	    public  int?	 CIP51ASSOC  {get; set;}
	    public  int?	 CIP51CERT4  {get; set;}
	    public  int?	 CIP51BACHL  {get; set;}
	    public  int?	 CIP52CERT1  {get; set;}
	    public  int?	 CIP52CERT2  {get; set;}
	    public  int?	 CIP52ASSOC  {get; set;}
	    public  int?	 CIP52CERT4  {get; set;}
	    public  int?	 CIP52BACHL  {get; set;}
	    public  int?	 CIP54CERT1  {get; set;}
	    public  int?	 CIP54CERT2  {get; set;}
	    public  int?	 CIP54ASSOC  {get; set;}
	    public  int?	 CIP54CERT4  {get; set;}
	    public  int?	 CIP54BACHL  {get; set;}


}
}
