using System;

namespace JonasTest.Core
{
	public class Student
	{
		public int UNITID { get; set; } 
		public int? UGDS	{ get; set; }
		public int? UG	{ get; set; }
		public decimal? UGDS_WHITE	{ get; set; }
		public decimal? UGDS_BLACK	{ get; set; }
		public decimal? UGDS_HISP	{ get; set; }
		public decimal? UGDS_ASIAN	{ get; set; }
		public decimal? UGDS_AIAN	{ get; set; }
		public decimal? UGDS_NHPI	{ get; set; }
		public decimal? UGDS_2MOR	{ get; set; }
		public decimal? UGDS_NRA	{ get; set; }
		public decimal? UGDS_UNKN	{ get; set; }
		public decimal? UGDS_WHITENH	{ get; set; }
		public decimal? UGDS_BLACKNH	{ get; set; }
		public decimal? UGDS_API	{ get; set; }
		public decimal? UGDS_AIANOLD	{ get; set; }
		public decimal? UGDS_HISPOLD	{ get; set; }
		public decimal? UG_NRA	{ get; set; }
		public decimal? UG_UNKN	{ get; set; }
		public decimal? UG_WHITENH	{ get; set; }
		public decimal? UG_BLACKNH	{ get; set; }
		public decimal? UG_API	{ get; set; }
		public decimal? UG_AIANOLD	{ get; set; }
		public decimal? UG_HISPOLD	{ get; set; }
		public decimal? PPTUG_EF	{ get; set; }
		public decimal? PPTUG_EF2	{ get; set; }
		public decimal? PFTFTUG1_EF	{ get; set; }
		public decimal? RET_FT4	{ get; set; }
		public decimal? RET_FTL4	{ get; set; }
		public decimal? RET_PT4	{ get; set; }
		public decimal? RET_PTL4	{ get; set; }
		public decimal? UG25ABV	{ get; set; }
		public decimal? INC_PCT_LO	{ get; set; }
		public decimal? DEP_STAT_PCT_IND	{ get; set; }
		public decimal? IND_INC_PCT_LO	{ get; set; }
		public decimal? DEP_INC_PCT_LO	{ get; set; }
		public decimal? PAR_ED_PCT_1STGEN	{ get; set; }
		public decimal? INC_PCT_M1	{ get; set; }
		public decimal? INC_PCT_M2	{ get; set; }
		public decimal? INC_PCT_H1	{ get; set; }
		public decimal? INC_PCT_H2	{ get; set; }
		public decimal? DEP_INC_PCT_M1	{ get; set; }
		public decimal? DEP_INC_PCT_M2	{ get; set; }
		public decimal? DEP_INC_PCT_H1	{ get; set; }
		public decimal? DEP_INC_PCT_H2	{ get; set; }
		public decimal? IND_INC_PCT_M1	{ get; set; }
		public decimal? IND_INC_PCT_M2	{ get; set; }
		public decimal? IND_INC_PCT_H1	{ get; set; }
		public decimal? IND_INC_PCT_H2	{ get; set; }
		public decimal? PAR_ED_PCT_MS	{ get; set; }
		public decimal? PAR_ED_PCT_HS	{ get; set; }
		public decimal? PAR_ED_PCT_PS	{ get; set; }
		public decimal? APPL_SCH_PCT_GE2	{ get; set; }
		public decimal? APPL_SCH_PCT_GE3	{ get; set; }
		public decimal? APPL_SCH_PCT_GE4	{ get; set; }
		public decimal? APPL_SCH_PCT_GE5	{ get; set; }
		public decimal? DEP_INC_AVG	{ get; set; }
		public decimal? IND_INC_AVG	{ get; set; }
		public int? INC_N	{ get; set; }
		public int? DEP_INC_N	{ get; set; }
		public int? IND_INC_N	{ get; set; }
		public int? DEP_STAT_N	{ get; set; }
		public int? PAR_ED_N	{ get; set; }
		public int? APPL_SCH_N	{ get; set; }
		public decimal? PELL_EVER	{ get; set; }
		public decimal? AGE_ENTRY	{ get; set; }
		public int? AGE_ENTRY_SQ	{ get; set; }
		public decimal?	 AGEGE24	{ get; set; }
		public decimal?	FEMALE	{ get; set; }
		public decimal?	MARRIED	{ get; set; }
		public decimal?	DEPENDENT	{ get; set; }
		public decimal?	VETERAN	{ get; set; }
		public decimal?	FIRST_GEN	{ get; set; }
		public decimal? FAMINC	{ get; set; }
		public decimal? MD_FAMINC	{ get; set; }
		public decimal? FAMINC_IND	{ get; set; }
		public int? LNFAMINC	{ get; set; }
		public int? LNFAMINC_IND	{ get; set; }
		public decimal? PCT_WHITE	{ get; set; }
		public decimal? PCT_BLACK	{ get; set; }
		public decimal? PCT_ASIAN	{ get; set; }
		public decimal? PCT_HISPANIC	{ get; set; }
		public decimal? PCT_BA	{ get; set; }
		public decimal? PCT_GRAD_PROF	{ get; set; }
		public decimal? PCT_BORN_US	{ get; set; }
		public int? MEDIAN_HH_INC	{ get; set; }
		public decimal? POVERTY_RATE	{ get; set; }
		public decimal? UNEMP_RATE	{ get; set; }
		public int? LN_MEDIAN_HH_INC	{ get; set; }
		public int? FSEND_COUNT	{ get; set; }
		public decimal? FSEND_1	{ get; set; }
		public decimal? FSEND_2	{ get; set; }
		public decimal? FSEND_3	{ get; set; }
		public decimal? FSEND_4	{ get; set; }
		public decimal? FSEND_5	{ get; set; }
		public decimal? UGDS_MEN	{ get; set; }
		public decimal? UGDS_WOMEN	{ get; set; }
		public int? D_PCTPELL_PCTFLOAN	{ get; set; }
		public int? UGNONDS	{ get; set; }
		public int? GRADS	{ get; set; }
		public decimal? RET_FT4_POOLED	{ get; set; }
		public decimal? RET_FTL4_POOLED	{ get; set; }
		public decimal? RET_PT4_POOLED	{ get; set; }
		public decimal? RET_PTL4_POOLED	{ get; set; }
		public decimal? RET_FT_DEN4_POOLED	{ get; set; }
		public decimal? RET_FT_DENL4_POOLED	{ get; set; }
		public decimal? RET_PT_DEN4_POOLED	{ get; set; }
		public decimal? RET_PT_DENL4_POOLED	{ get; set; }
		public int? POOLYRSRET_FT	{ get; set; }
		public int? POOLYRSRET_PT	{ get; set; }
		public decimal? RET_FT4_POOLED_SUPP	{ get; set; }
		public decimal? RET_FTL4_POOLED_SUPP	{ get; set; }
		public decimal? RET_PT4_POOLED_SUPP	{ get; set; }
		public decimal? RET_PTL4_POOLED_SUPP	{ get; set; }
	}
}