using System;

namespace JonasTest.Core
{
	public class TitleIV
	{
		public int   UNITID								{ get; set; }
	public	decimal? DEATH_YR2_RT						 {get; set;}
	public	decimal? COMP_ORIG_YR2_RT					 {get; set;}
	public	decimal? COMP_4YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? COMP_2YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? WDRAW_ORIG_YR2_RT					 {get; set;}
	public	decimal? WDRAW_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? WDRAW_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? ENRL_ORIG_YR2_RT					 {get; set;}
	public	decimal? ENRL_4YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? ENRL_2YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? UNKN_ORIG_YR2_RT					 {get; set;}
	public	decimal? UNKN_4YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? UNKN_2YR_TRANS_YR2_RT				 {get; set;}
	public	decimal? LO_INC_DEATH_YR2_RT				 {get; set;}
	public	decimal? LO_INC_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? LO_INC_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? LO_INC_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? LO_INC_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? LO_INC_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_DEATH_YR2_RT				 {get; set;}
	public	decimal? MD_INC_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? MD_INC_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? MD_INC_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? MD_INC_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? MD_INC_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_DEATH_YR2_RT				 {get; set;}
	public	decimal? HI_INC_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? HI_INC_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? HI_INC_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? HI_INC_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? HI_INC_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? DEP_DEATH_YR2_RT					 {get; set;}
	public	decimal? DEP_COMP_ORIG_YR2_RT				 {get; set;}
	public	decimal? DEP_COMP_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? DEP_COMP_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? DEP_WDRAW_ORIG_YR2_RT				 {get; set;}
	public	decimal? DEP_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? DEP_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? DEP_ENRL_ORIG_YR2_RT				 {get; set;}
	public	decimal? DEP_ENRL_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? DEP_ENRL_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? DEP_UNKN_ORIG_YR2_RT				 {get; set;}
	public	decimal? DEP_UNKN_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? DEP_UNKN_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_DEATH_YR2_RT					 {get; set;}
	public	decimal? IND_COMP_ORIG_YR2_RT				 {get; set;}
	public	decimal? IND_COMP_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_COMP_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_WDRAW_ORIG_YR2_RT				 {get; set;}
	public	decimal? IND_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? IND_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? IND_ENRL_ORIG_YR2_RT				 {get; set;}
	public	decimal? IND_ENRL_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_ENRL_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_UNKN_ORIG_YR2_RT				 {get; set;}
	public	decimal? IND_UNKN_4YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? IND_UNKN_2YR_TRANS_YR2_RT			 {get; set;}
	public	decimal? FEMALE_DEATH_YR2_RT				 {get; set;}
	public	decimal? FEMALE_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? FEMALE_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? FEMALE_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? FEMALE_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? FEMALE_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_DEATH_YR2_RT					 {get; set;}
	public	decimal? MALE_COMP_ORIG_YR2_RT				 {get; set;}
	public	decimal? MALE_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? MALE_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_ENRL_ORIG_YR2_RT				 {get; set;}
	public	decimal? MALE_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_UNKN_ORIG_YR2_RT				 {get; set;}
	public	decimal? MALE_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? MALE_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_DEATH_YR2_RT					 {get; set;}
	public	decimal? PELL_COMP_ORIG_YR2_RT				 {get; set;}
	public	decimal? PELL_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? PELL_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_ENRL_ORIG_YR2_RT				 {get; set;}
	public	decimal? PELL_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_UNKN_ORIG_YR2_RT				 {get; set;}
	public	decimal? PELL_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? PELL_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_DEATH_YR2_RT				 {get; set;}
	public	decimal? NOPELL_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOPELL_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOPELL_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOPELL_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOPELL_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_DEATH_YR2_RT					 {get; set;}
	public	decimal? LOAN_COMP_ORIG_YR2_RT				 {get; set;}
	public	decimal? LOAN_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? LOAN_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_ENRL_ORIG_YR2_RT				 {get; set;}
	public	decimal? LOAN_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_UNKN_ORIG_YR2_RT				 {get; set;}
	public	decimal? LOAN_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? LOAN_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_DEATH_YR2_RT				 {get; set;}
	public	decimal? NOLOAN_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOLOAN_COMP_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_COMP_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOLOAN_WDRAW_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOLOAN_ENRL_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? NOLOAN_UNKN_4YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_2YR_TRANS_YR2_RT		 {get; set;}
	public	decimal? FIRSTGEN_DEATH_YR2_RT				 {get; set;}
	public	decimal? FIRSTGEN_COMP_ORIG_YR2_RT			 {get; set;}
	public	decimal? FIRSTGEN_COMP_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_COMP_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_ORIG_YR2_RT		 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_ORIG_YR2_RT			 {get; set;}
	public	decimal? FIRSTGEN_ENRL_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_ORIG_YR2_RT			 {get; set;}
	public	decimal? FIRSTGEN_UNKN_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_DEATH_YR2_RT			 {get; set;}
	public	decimal? NOT1STGEN_COMP_ORIG_YR2_RT		 {get; set;}
	public	decimal? NOT1STGEN_COMP_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_COMP_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_ORIG_YR2_RT		 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_ORIG_YR2_RT		 {get; set;}
	public	decimal? NOT1STGEN_ENRL_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_ORIG_YR2_RT		 {get; set;}
	public	decimal? NOT1STGEN_UNKN_4YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_2YR_TRANS_YR2_RT	 {get; set;}
	public	decimal? DEATH_YR3_RT						 {get; set;}
	public	decimal? COMP_ORIG_YR3_RT					 {get; set;}
	public	decimal? COMP_4YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? COMP_2YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? WDRAW_ORIG_YR3_RT					 {get; set;}
	public	decimal? WDRAW_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? WDRAW_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? ENRL_ORIG_YR3_RT					 {get; set;}
	public	decimal? ENRL_4YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? ENRL_2YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? UNKN_ORIG_YR3_RT					 {get; set;}
	public	decimal? UNKN_4YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? UNKN_2YR_TRANS_YR3_RT				 {get; set;}
	public	decimal? LO_INC_DEATH_YR3_RT				 {get; set;}
	public	decimal? LO_INC_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? LO_INC_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? LO_INC_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? LO_INC_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? LO_INC_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_DEATH_YR3_RT				 {get; set;}
	public	decimal? MD_INC_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? MD_INC_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? MD_INC_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? MD_INC_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? MD_INC_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_DEATH_YR3_RT				 {get; set;}
	public	decimal? HI_INC_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? HI_INC_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? HI_INC_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? HI_INC_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? HI_INC_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? DEP_DEATH_YR3_RT					 {get; set;}
	public	decimal? DEP_COMP_ORIG_YR3_RT				 {get; set;}
	public	decimal? DEP_COMP_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? DEP_COMP_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? DEP_WDRAW_ORIG_YR3_RT				 {get; set;}
	public	decimal? DEP_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? DEP_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? DEP_ENRL_ORIG_YR3_RT				 {get; set;}
	public	decimal? DEP_ENRL_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? DEP_ENRL_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? DEP_UNKN_ORIG_YR3_RT				 {get; set;}
	public	decimal? DEP_UNKN_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? DEP_UNKN_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_DEATH_YR3_RT					 {get; set;}
	public	decimal? IND_COMP_ORIG_YR3_RT				 {get; set;}
	public	decimal? IND_COMP_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_COMP_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_WDRAW_ORIG_YR3_RT				 {get; set;}
	public	decimal? IND_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? IND_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? IND_ENRL_ORIG_YR3_RT				 {get; set;}
	public	decimal? IND_ENRL_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_ENRL_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_UNKN_ORIG_YR3_RT				 {get; set;}
	public	decimal? IND_UNKN_4YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? IND_UNKN_2YR_TRANS_YR3_RT			 {get; set;}
	public	decimal? FEMALE_DEATH_YR3_RT				 {get; set;}
	public	decimal? FEMALE_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? FEMALE_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? FEMALE_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? FEMALE_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? FEMALE_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_DEATH_YR3_RT					 {get; set;}
	public	decimal? MALE_COMP_ORIG_YR3_RT				 {get; set;}
	public	decimal? MALE_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? MALE_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_ENRL_ORIG_YR3_RT				 {get; set;}
	public	decimal? MALE_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_UNKN_ORIG_YR3_RT				 {get; set;}
	public	decimal? MALE_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? MALE_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_DEATH_YR3_RT					 {get; set;}
	public	decimal? PELL_COMP_ORIG_YR3_RT				 {get; set;}
	public	decimal? PELL_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? PELL_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_ENRL_ORIG_YR3_RT				 {get; set;}
	public	decimal? PELL_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_UNKN_ORIG_YR3_RT				 {get; set;}
	public	decimal? PELL_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? PELL_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_DEATH_YR3_RT				 {get; set;}
	public	decimal? NOPELL_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOPELL_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOPELL_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOPELL_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOPELL_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_DEATH_YR3_RT					 {get; set;}
	public	decimal? LOAN_COMP_ORIG_YR3_RT				 {get; set;}
	public	decimal? LOAN_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? LOAN_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_ENRL_ORIG_YR3_RT				 {get; set;}
	public	decimal? LOAN_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_UNKN_ORIG_YR3_RT				 {get; set;}
	public	decimal? LOAN_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? LOAN_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_DEATH_YR3_RT				 {get; set;}
	public	decimal? NOLOAN_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOLOAN_COMP_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_COMP_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOLOAN_WDRAW_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOLOAN_ENRL_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? NOLOAN_UNKN_4YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_2YR_TRANS_YR3_RT		 {get; set;}
	public	decimal? FIRSTGEN_DEATH_YR3_RT				 {get; set;}
	public	decimal? FIRSTGEN_COMP_ORIG_YR3_RT			 {get; set;}
	public	decimal? FIRSTGEN_COMP_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_COMP_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_ORIG_YR3_RT		 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_ORIG_YR3_RT			 {get; set;}
	public	decimal? FIRSTGEN_ENRL_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_ORIG_YR3_RT			 {get; set;}
	public	decimal? FIRSTGEN_UNKN_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_DEATH_YR3_RT			 {get; set;}
	public	decimal? NOT1STGEN_COMP_ORIG_YR3_RT		 {get; set;}
	public	decimal? NOT1STGEN_COMP_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_COMP_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_ORIG_YR3_RT		 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_ORIG_YR3_RT		 {get; set;}
	public	decimal? NOT1STGEN_ENRL_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_ORIG_YR3_RT		 {get; set;}
	public	decimal? NOT1STGEN_UNKN_4YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_2YR_TRANS_YR3_RT	 {get; set;}
	public	decimal? DEATH_YR4_RT						 {get; set;}
	public	decimal? COMP_ORIG_YR4_RT					 {get; set;}
	public	decimal? COMP_4YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? COMP_2YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? WDRAW_ORIG_YR4_RT					 {get; set;}
	public	decimal? WDRAW_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? WDRAW_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? ENRL_ORIG_YR4_RT					 {get; set;}
	public	decimal? ENRL_4YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? ENRL_2YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? UNKN_ORIG_YR4_RT					 {get; set;}
	public	decimal? UNKN_4YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? UNKN_2YR_TRANS_YR4_RT				 {get; set;}
	public	decimal? LO_INC_DEATH_YR4_RT				 {get; set;}
	public	decimal? LO_INC_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? LO_INC_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? LO_INC_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? LO_INC_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? LO_INC_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_DEATH_YR4_RT				 {get; set;}
	public	decimal? MD_INC_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? MD_INC_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? MD_INC_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? MD_INC_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? MD_INC_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_DEATH_YR4_RT				 {get; set;}
	public	decimal? HI_INC_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? HI_INC_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? HI_INC_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? HI_INC_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? HI_INC_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? DEP_DEATH_YR4_RT					 {get; set;}
	public	decimal? DEP_COMP_ORIG_YR4_RT				 {get; set;}
	public	decimal? DEP_COMP_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? DEP_COMP_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? DEP_WDRAW_ORIG_YR4_RT				 {get; set;}
	public	decimal? DEP_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? DEP_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? DEP_ENRL_ORIG_YR4_RT				 {get; set;}
	public	decimal? DEP_ENRL_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? DEP_ENRL_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? DEP_UNKN_ORIG_YR4_RT				 {get; set;}
	public	decimal? DEP_UNKN_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? DEP_UNKN_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_DEATH_YR4_RT					 {get; set;}
	public	decimal? IND_COMP_ORIG_YR4_RT				 {get; set;}
	public	decimal? IND_COMP_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_COMP_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_WDRAW_ORIG_YR4_RT				 {get; set;}
	public	decimal? IND_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? IND_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? IND_ENRL_ORIG_YR4_RT				 {get; set;}
	public	decimal? IND_ENRL_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_ENRL_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_UNKN_ORIG_YR4_RT				 {get; set;}
	public	decimal? IND_UNKN_4YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? IND_UNKN_2YR_TRANS_YR4_RT			 {get; set;}
	public	decimal? FEMALE_DEATH_YR4_RT				 {get; set;}
	public	decimal? FEMALE_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? FEMALE_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? FEMALE_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? FEMALE_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? FEMALE_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_DEATH_YR4_RT					 {get; set;}
	public	decimal? MALE_COMP_ORIG_YR4_RT				 {get; set;}
	public	decimal? MALE_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? MALE_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_ENRL_ORIG_YR4_RT				 {get; set;}
	public	decimal? MALE_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_UNKN_ORIG_YR4_RT				 {get; set;}
	public	decimal? MALE_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? MALE_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_DEATH_YR4_RT					 {get; set;}
	public	decimal? PELL_COMP_ORIG_YR4_RT				 {get; set;}
	public	decimal? PELL_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? PELL_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_ENRL_ORIG_YR4_RT				 {get; set;}
	public	decimal? PELL_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_UNKN_ORIG_YR4_RT				 {get; set;}
	public	decimal? PELL_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? PELL_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_DEATH_YR4_RT				 {get; set;}
	public	decimal? NOPELL_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOPELL_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOPELL_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOPELL_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOPELL_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_DEATH_YR4_RT					 {get; set;}
	public	decimal? LOAN_COMP_ORIG_YR4_RT				 {get; set;}
	public	decimal? LOAN_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? LOAN_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_ENRL_ORIG_YR4_RT				 {get; set;}
	public	decimal? LOAN_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_UNKN_ORIG_YR4_RT				 {get; set;}
	public	decimal? LOAN_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? LOAN_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_DEATH_YR4_RT				 {get; set;}
	public	decimal? NOLOAN_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOLOAN_COMP_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_COMP_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOLOAN_WDRAW_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOLOAN_ENRL_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? NOLOAN_UNKN_4YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_2YR_TRANS_YR4_RT		 {get; set;}
	public	decimal? FIRSTGEN_DEATH_YR4_RT				 {get; set;}
	public	decimal? FIRSTGEN_COMP_ORIG_YR4_RT			 {get; set;}
	public	decimal? FIRSTGEN_COMP_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_COMP_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_ORIG_YR4_RT		 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_ORIG_YR4_RT			 {get; set;}
	public	decimal? FIRSTGEN_ENRL_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_ORIG_YR4_RT			 {get; set;}
	public	decimal? FIRSTGEN_UNKN_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_DEATH_YR4_RT			 {get; set;}
	public	decimal? NOT1STGEN_COMP_ORIG_YR4_RT		 {get; set;}
	public	decimal? NOT1STGEN_COMP_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_COMP_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_ORIG_YR4_RT		 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_ORIG_YR4_RT		 {get; set;}
	public	decimal? NOT1STGEN_ENRL_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_ORIG_YR4_RT		 {get; set;}
	public	decimal? NOT1STGEN_UNKN_4YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_2YR_TRANS_YR4_RT	 {get; set;}
	public	decimal? DEATH_YR6_RT						 {get; set;}
	public	decimal? COMP_ORIG_YR6_RT					 {get; set;}
	public	decimal? COMP_4YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? COMP_2YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? WDRAW_ORIG_YR6_RT					 {get; set;}
	public	decimal? WDRAW_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? WDRAW_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? ENRL_ORIG_YR6_RT					 {get; set;}
	public	decimal? ENRL_4YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? ENRL_2YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? UNKN_ORIG_YR6_RT					 {get; set;}
	public	decimal? UNKN_4YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? UNKN_2YR_TRANS_YR6_RT				 {get; set;}
	public	decimal? LO_INC_DEATH_YR6_RT				 {get; set;}
	public	decimal? LO_INC_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? LO_INC_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? LO_INC_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? LO_INC_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? LO_INC_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_DEATH_YR6_RT				 {get; set;}
	public	decimal? MD_INC_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? MD_INC_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? MD_INC_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? MD_INC_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? MD_INC_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_DEATH_YR6_RT				 {get; set;}
	public	decimal? HI_INC_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? HI_INC_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? HI_INC_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? HI_INC_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? HI_INC_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? DEP_DEATH_YR6_RT					 {get; set;}
	public	decimal? DEP_COMP_ORIG_YR6_RT				 {get; set;}
	public	decimal? DEP_COMP_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? DEP_COMP_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? DEP_WDRAW_ORIG_YR6_RT				 {get; set;}
	public	decimal? DEP_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? DEP_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? DEP_ENRL_ORIG_YR6_RT				 {get; set;}
	public	decimal? DEP_ENRL_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? DEP_ENRL_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? DEP_UNKN_ORIG_YR6_RT				 {get; set;}
	public	decimal? DEP_UNKN_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? DEP_UNKN_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_DEATH_YR6_RT					 {get; set;}
	public	decimal? IND_COMP_ORIG_YR6_RT				 {get; set;}
	public	decimal? IND_COMP_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_COMP_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_WDRAW_ORIG_YR6_RT				 {get; set;}
	public	decimal? IND_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? IND_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? IND_ENRL_ORIG_YR6_RT				 {get; set;}
	public	decimal? IND_ENRL_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_ENRL_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_UNKN_ORIG_YR6_RT				 {get; set;}
	public	decimal? IND_UNKN_4YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? IND_UNKN_2YR_TRANS_YR6_RT			 {get; set;}
	public	decimal? FEMALE_DEATH_YR6_RT				 {get; set;}
	public	decimal? FEMALE_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? FEMALE_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? FEMALE_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? FEMALE_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? FEMALE_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_DEATH_YR6_RT					 {get; set;}
	public	decimal? MALE_COMP_ORIG_YR6_RT				 {get; set;}
	public	decimal? MALE_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? MALE_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_ENRL_ORIG_YR6_RT				 {get; set;}
	public	decimal? MALE_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_UNKN_ORIG_YR6_RT				 {get; set;}
	public	decimal? MALE_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? MALE_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_DEATH_YR6_RT					 {get; set;}
	public	decimal? PELL_COMP_ORIG_YR6_RT				 {get; set;}
	public	decimal? PELL_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? PELL_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_ENRL_ORIG_YR6_RT				 {get; set;}
	public	decimal? PELL_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_UNKN_ORIG_YR6_RT				 {get; set;}
	public	decimal? PELL_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? PELL_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_DEATH_YR6_RT				 {get; set;}
	public	decimal? NOPELL_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOPELL_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOPELL_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOPELL_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOPELL_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_DEATH_YR6_RT					 {get; set;}
	public	decimal? LOAN_COMP_ORIG_YR6_RT				 {get; set;}
	public	decimal? LOAN_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? LOAN_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_ENRL_ORIG_YR6_RT				 {get; set;}
	public	decimal? LOAN_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_UNKN_ORIG_YR6_RT				 {get; set;}
	public	decimal? LOAN_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? LOAN_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_DEATH_YR6_RT				 {get; set;}
	public	decimal? NOLOAN_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOLOAN_COMP_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_COMP_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOLOAN_WDRAW_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOLOAN_ENRL_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? NOLOAN_UNKN_4YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_2YR_TRANS_YR6_RT		 {get; set;}
	public	decimal? FIRSTGEN_DEATH_YR6_RT				 {get; set;}
	public	decimal? FIRSTGEN_COMP_ORIG_YR6_RT			 {get; set;}
	public	decimal? FIRSTGEN_COMP_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_COMP_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_ORIG_YR6_RT		 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_ORIG_YR6_RT			 {get; set;}
	public	decimal? FIRSTGEN_ENRL_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_ORIG_YR6_RT			 {get; set;}
	public	decimal? FIRSTGEN_UNKN_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_DEATH_YR6_RT			 {get; set;}
	public	decimal? NOT1STGEN_COMP_ORIG_YR6_RT		 {get; set;}
	public	decimal? NOT1STGEN_COMP_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_COMP_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_ORIG_YR6_RT		 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_ORIG_YR6_RT		 {get; set;}
	public	decimal? NOT1STGEN_ENRL_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_ORIG_YR6_RT		 {get; set;}
	public	decimal? NOT1STGEN_UNKN_4YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_2YR_TRANS_YR6_RT	 {get; set;}
	public	decimal? DEATH_YR8_RT						 {get; set;}
	public	decimal? COMP_ORIG_YR8_RT					 {get; set;}
	public	decimal? COMP_4YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? COMP_2YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? WDRAW_ORIG_YR8_RT					 {get; set;}
	public	decimal? WDRAW_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? WDRAW_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? ENRL_ORIG_YR8_RT					 {get; set;}
	public	decimal? ENRL_4YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? ENRL_2YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? UNKN_ORIG_YR8_RT					 {get; set;}
	public	decimal? UNKN_4YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? UNKN_2YR_TRANS_YR8_RT				 {get; set;}
	public	decimal? LO_INC_DEATH_YR8_RT				 {get; set;}
	public	decimal? LO_INC_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? LO_INC_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? LO_INC_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? LO_INC_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? LO_INC_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LO_INC_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_DEATH_YR8_RT				 {get; set;}
	public	decimal? MD_INC_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? MD_INC_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? MD_INC_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? MD_INC_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? MD_INC_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MD_INC_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_DEATH_YR8_RT				 {get; set;}
	public	decimal? HI_INC_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? HI_INC_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? HI_INC_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? HI_INC_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? HI_INC_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? HI_INC_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? DEP_DEATH_YR8_RT					 {get; set;}
	public	decimal? DEP_COMP_ORIG_YR8_RT				 {get; set;}
	public	decimal? DEP_COMP_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? DEP_COMP_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? DEP_WDRAW_ORIG_YR8_RT				 {get; set;}
	public	decimal? DEP_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? DEP_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? DEP_ENRL_ORIG_YR8_RT				 {get; set;}
	public	decimal? DEP_ENRL_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? DEP_ENRL_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? DEP_UNKN_ORIG_YR8_RT				 {get; set;}
	public	decimal? DEP_UNKN_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? DEP_UNKN_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_DEATH_YR8_RT					 {get; set;}
	public	decimal? IND_COMP_ORIG_YR8_RT				 {get; set;}
	public	decimal? IND_COMP_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_COMP_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_WDRAW_ORIG_YR8_RT				 {get; set;}
	public	decimal? IND_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? IND_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? IND_ENRL_ORIG_YR8_RT				 {get; set;}
	public	decimal? IND_ENRL_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_ENRL_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_UNKN_ORIG_YR8_RT				 {get; set;}
	public	decimal? IND_UNKN_4YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? IND_UNKN_2YR_TRANS_YR8_RT			 {get; set;}
	public	decimal? FEMALE_DEATH_YR8_RT				 {get; set;}
	public	decimal? FEMALE_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? FEMALE_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? FEMALE_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? FEMALE_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? FEMALE_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FEMALE_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_DEATH_YR8_RT					 {get; set;}
	public	decimal? MALE_COMP_ORIG_YR8_RT				 {get; set;}
	public	decimal? MALE_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? MALE_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_ENRL_ORIG_YR8_RT				 {get; set;}
	public	decimal? MALE_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_UNKN_ORIG_YR8_RT				 {get; set;}
	public	decimal? MALE_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? MALE_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_DEATH_YR8_RT					 {get; set;}
	public	decimal? PELL_COMP_ORIG_YR8_RT				 {get; set;}
	public	decimal? PELL_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? PELL_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_ENRL_ORIG_YR8_RT				 {get; set;}
	public	decimal? PELL_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_UNKN_ORIG_YR8_RT				 {get; set;}
	public	decimal? PELL_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? PELL_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_DEATH_YR8_RT				 {get; set;}
	public	decimal? NOPELL_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOPELL_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOPELL_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOPELL_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOPELL_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOPELL_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_DEATH_YR8_RT					 {get; set;}
	public	decimal? LOAN_COMP_ORIG_YR8_RT				 {get; set;}
	public	decimal? LOAN_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? LOAN_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_ENRL_ORIG_YR8_RT				 {get; set;}
	public	decimal? LOAN_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_UNKN_ORIG_YR8_RT				 {get; set;}
	public	decimal? LOAN_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? LOAN_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_DEATH_YR8_RT				 {get; set;}
	public	decimal? NOLOAN_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOLOAN_COMP_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_COMP_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOLOAN_WDRAW_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_WDRAW_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOLOAN_ENRL_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_ENRL_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? NOLOAN_UNKN_4YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? NOLOAN_UNKN_2YR_TRANS_YR8_RT		 {get; set;}
	public	decimal? FIRSTGEN_DEATH_YR8_RT				 {get; set;}
	public	decimal? FIRSTGEN_COMP_ORIG_YR8_RT			 {get; set;}
	public	decimal? FIRSTGEN_COMP_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_COMP_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_ORIG_YR8_RT		 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_WDRAW_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_ORIG_YR8_RT			 {get; set;}
	public	decimal? FIRSTGEN_ENRL_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_ENRL_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_ORIG_YR8_RT			 {get; set;}
	public	decimal? FIRSTGEN_UNKN_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? FIRSTGEN_UNKN_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_DEATH_YR8_RT			 {get; set;}
	public	decimal? NOT1STGEN_COMP_ORIG_YR8_RT		 {get; set;}
	public	decimal? NOT1STGEN_COMP_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_COMP_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_ORIG_YR8_RT		 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_WDRAW_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_ORIG_YR8_RT		 {get; set;}
	public	decimal? NOT1STGEN_ENRL_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_ENRL_2YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_ORIG_YR8_RT		 {get; set;}
	public	decimal? NOT1STGEN_UNKN_4YR_TRANS_YR8_RT	 {get; set;}
	public	decimal? NOT1STGEN_UNKN_2YR_TRANS_YR8_RT	 {get; set;}
	

	}
}
