use ScoreCard

CREATE TABLE [cscData].[Root](
	UNITID	INT NOT NULL
	,OPEID	INT	NOT NULL
	,OPEID6	INT	NOT NULL
	,LATITUDE	DECIMAL(5,2) NULL
	,LONGITUDE	DECIMAL(5,2) NULL
	CONSTRAINT PK_Root_UNITID PRIMARY KEY CLUSTERED (UNITID) 
	) 
