USE [ScoreCard]
GO


CREATE TABLE [cscData].[Earnings](
	[UNITID] [int] NOT NULL,
	[COUNT_ED] [int] NULL,
	[COUNT_NWNE_P10] [int] NULL,
	[COUNT_WNE_P10] [int] NULL,
	[MN_EARN_WNE_P10] [int] NULL,
	[MD_EARN_WNE_P10] [int] NULL,
	[PCT10_EARN_WNE_P10] [int] NULL,
	[PCT25_EARN_WNE_P10] [int] NULL,
	[PCT75_EARN_WNE_P10] [int] NULL,
	[PCT90_EARN_WNE_P10] [int] NULL,
	[SD_EARN_WNE_P10] [int] NULL,
	[COUNT_WNE_INC1_P10] [int] NULL,
	[COUNT_WNE_INC2_P10] [int] NULL,
	[COUNT_WNE_INC3_P10] [int] NULL,
	[COUNT_WNE_INDEP0_INC1_P10] [int] NULL,
	[COUNT_WNE_INDEP0_P10] [int] NULL,
	[COUNT_WNE_INDEP1_P10] [int] NULL,
	[COUNT_WNE_MALE0_P10] [int] NULL,
	[COUNT_WNE_MALE1_P10] [int] NULL,
	[GT_25K_P10] DECIMAL(5,2) NULL,
	[GT_28K_P10] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INC1_P10] [int] NULL,
	[MN_EARN_WNE_INC2_P10] [int] NULL,
	[MN_EARN_WNE_INC3_P10] [int] NULL,
	[MN_EARN_WNE_INDEP0_INC1_P10] [int] NULL,
	[MN_EARN_WNE_INDEP0_P10] [int] NULL,
	[MN_EARN_WNE_INDEP1_P10] [int] NULL,
	[MN_EARN_WNE_MALE0_P10] [int] NULL,
	[MN_EARN_WNE_MALE1_P10] [int] NULL,
	[COUNT_NWNE_P6] [int] NULL,
	[COUNT_WNE_P6] [int] NULL,
	[MN_EARN_WNE_P6] [int] NULL,
	[MD_EARN_WNE_P6] [int] NULL,
	[PCT10_EARN_WNE_P6] [int] NULL,
	[PCT25_EARN_WNE_P6] [int] NULL,
	[PCT75_EARN_WNE_P6] [int] NULL,
	[PCT90_EARN_WNE_P6] [int] NULL,
	[SD_EARN_WNE_P6] [int] NULL,
	[COUNT_WNE_INC1_P6] [int] NULL,
	[COUNT_WNE_INC2_P6] [int] NULL,
	[COUNT_WNE_INC3_P6] [int] NULL,
	[COUNT_WNE_INDEP0_INC1_P6] [int] NULL,
	[COUNT_WNE_INDEP0_P6] [int] NULL,
	[COUNT_WNE_INDEP1_P6] [int] NULL,
	[COUNT_WNE_MALE0_P6] [int] NULL,
	[COUNT_WNE_MALE1_P6] [int] NULL,
	[GT_25K_P6] DECIMAL(5,2) NULL,
	[GT_28K_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INC1_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INC2_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INC3_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INDEP0_INC1_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INDEP0_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_INDEP1_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_MALE0_P6] DECIMAL(5,2) NULL,
	[MN_EARN_WNE_MALE1_P6] DECIMAL(5,2) NULL,
	[COUNT_NWNE_P7] DECIMAL(5,2) NULL,
	[COUNT_WNE_P7] [int] NULL,
	[MN_EARN_WNE_P7] DECIMAL(5,2) NULL,
	[SD_EARN_WNE_P7] DECIMAL(5,2) NULL,
	[GT_25K_P7] DECIMAL(5,2) NULL,
	[COUNT_NWNE_P8] [int] NULL,
	[COUNT_WNE_P8] [int] NULL,
	[MN_EARN_WNE_P8] DECIMAL(5,2) NULL,
	[MD_EARN_WNE_P8] DECIMAL(5,2) NULL,
	[PCT10_EARN_WNE_P8] [int] NULL,
	[PCT25_EARN_WNE_P8] [int] NULL,
	[PCT75_EARN_WNE_P8] [int] NULL,
	[PCT90_EARN_WNE_P8] [int] NULL,
	[SD_EARN_WNE_P8] DECIMAL(5,2) NULL,
	[GT_25K_P8] DECIMAL(5,2) NULL,
	[GT_28K_P8] DECIMAL(5,2) NULL,
	[COUNT_NWNE_P9] [int] NULL,
	[COUNT_WNE_P9] [int] NULL,
	[MN_EARN_WNE_P9] DECIMAL(5,2) NULL,
	[SD_EARN_WNE_P9] DECIMAL(5,2) NULL,
	[GT_25K_P9] DECIMAL(5,2) NULL,
 CONSTRAINT [PK_Earning_UNITID] PRIMARY KEY CLUSTERED 
(
	[UNITID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [cscData].[Earnings]  WITH CHECK ADD  CONSTRAINT [FK_Earning_Root_UNITID] FOREIGN KEY([UNITID])
REFERENCES [cscData].[Root] ([UNITID])
GO

ALTER TABLE [cscData].[Earnings] CHECK CONSTRAINT [FK_Earning_Root_UNITID]
GO


