using System;
using System.Collections.Generic;

namespace JonasTest.Data.Model
{
    public partial class Academics
    {
        public int Unitid { get; set; }
        public decimal? Pcip01 { get; set; }
        public decimal? Pcip03 { get; set; }
        public decimal? Pcip04 { get; set; }
        public decimal? Pcip05 { get; set; }
        public decimal? Pcip09 { get; set; }
        public decimal? Pcip10 { get; set; }
        public decimal? Pcip11 { get; set; }
        public decimal? Pcip12 { get; set; }
        public decimal? Pcip13 { get; set; }
        public decimal? Pcip14 { get; set; }
        public decimal? Pcip15 { get; set; }
        public decimal? Pcip16 { get; set; }
        public decimal? Pcip19 { get; set; }
        public decimal? Pcip22 { get; set; }
        public decimal? Pcip23 { get; set; }
        public decimal? Pcip24 { get; set; }
        public decimal? Pcip25 { get; set; }
        public decimal? Pcip26 { get; set; }
        public decimal? Pcip27 { get; set; }
        public decimal? Pcip29 { get; set; }
        public decimal? Pcip30 { get; set; }
        public decimal? Pcip31 { get; set; }
        public decimal? Pcip38 { get; set; }
        public decimal? Pcip39 { get; set; }
        public decimal? Pcip40 { get; set; }
        public decimal? Pcip41 { get; set; }
        public decimal? Pcip42 { get; set; }
        public decimal? Pcip43 { get; set; }
        public decimal? Pcip44 { get; set; }
        public decimal? Pcip45 { get; set; }
        public decimal? Pcip46 { get; set; }
        public decimal? Pcip47 { get; set; }
        public decimal? Pcip48 { get; set; }
        public decimal? Pcip49 { get; set; }
        public decimal? Pcip50 { get; set; }
        public decimal? Pcip51 { get; set; }
        public decimal? Pcip52 { get; set; }
        public decimal? Pcip54 { get; set; }
        public int? Cip01cert1 { get; set; }
        public int? Cip01cert2 { get; set; }
        public int? Cip01assoc { get; set; }
        public int? Cip01cert4 { get; set; }
        public int? Cip01bachl { get; set; }
        public int? Cip03cert1 { get; set; }
        public int? Cip03cert2 { get; set; }
        public int? Cip03assoc { get; set; }
        public int? Cip03cert4 { get; set; }
        public int? Cip03bachl { get; set; }
        public int? Cip04cert1 { get; set; }
        public int? Cip04cert2 { get; set; }
        public int? Cip04assoc { get; set; }
        public int? Cip04cert4 { get; set; }
        public int? Cip04bachl { get; set; }
        public int? Cip05cert1 { get; set; }
        public int? Cip05cert2 { get; set; }
        public int? Cip05assoc { get; set; }
        public int? Cip05cert4 { get; set; }
        public int? Cip05bachl { get; set; }
        public int? Cip09cert1 { get; set; }
        public int? Cip09cert2 { get; set; }
        public int? Cip09assoc { get; set; }
        public int? Cip09cert4 { get; set; }
        public int? Cip09bachl { get; set; }
        public int? Cip10cert1 { get; set; }
        public int? Cip10cert2 { get; set; }
        public int? Cip10assoc { get; set; }
        public int? Cip10cert4 { get; set; }
        public int? Cip10bachl { get; set; }
        public int? Cip11cert1 { get; set; }
        public int? Cip11cert2 { get; set; }
        public int? Cip11assoc { get; set; }
        public int? Cip11cert4 { get; set; }
        public int? Cip11bachl { get; set; }
        public int? Cip12cert1 { get; set; }
        public int? Cip12cert2 { get; set; }
        public int? Cip12assoc { get; set; }
        public int? Cip12cert4 { get; set; }
        public int? Cip12bachl { get; set; }
        public int? Cip13cert1 { get; set; }
        public int? Cip13cert2 { get; set; }
        public int? Cip13assoc { get; set; }
        public int? Cip13cert4 { get; set; }
        public int? Cip13bachl { get; set; }
        public int? Cip14cert1 { get; set; }
        public int? Cip14cert2 { get; set; }
        public int? Cip14assoc { get; set; }
        public int? Cip14cert4 { get; set; }
        public int? Cip14bachl { get; set; }
        public int? Cip15cert1 { get; set; }
        public int? Cip15cert2 { get; set; }
        public int? Cip15assoc { get; set; }
        public int? Cip15cert4 { get; set; }
        public int? Cip15bachl { get; set; }
        public int? Cip16cert1 { get; set; }
        public int? Cip16cert2 { get; set; }
        public int? Cip16assoc { get; set; }
        public int? Cip16cert4 { get; set; }
        public int? Cip16bachl { get; set; }
        public int? Cip19cert1 { get; set; }
        public int? Cip19cert2 { get; set; }
        public int? Cip19assoc { get; set; }
        public int? Cip19cert4 { get; set; }
        public int? Cip19bachl { get; set; }
        public int? Cip22cert1 { get; set; }
        public int? Cip22cert2 { get; set; }
        public int? Cip22assoc { get; set; }
        public int? Cip22cert4 { get; set; }
        public int? Cip22bachl { get; set; }
        public int? Cip23cert1 { get; set; }
        public int? Cip23cert2 { get; set; }
        public int? Cip23assoc { get; set; }
        public int? Cip23cert4 { get; set; }
        public int? Cip23bachl { get; set; }
        public int? Cip24cert1 { get; set; }
        public int? Cip24cert2 { get; set; }
        public int? Cip24assoc { get; set; }
        public int? Cip24cert4 { get; set; }
        public int? Cip24bachl { get; set; }
        public int? Cip25cert1 { get; set; }
        public int? Cip25cert2 { get; set; }
        public int? Cip25assoc { get; set; }
        public int? Cip25cert4 { get; set; }
        public int? Cip25bachl { get; set; }
        public int? Cip26cert1 { get; set; }
        public int? Cip26cert2 { get; set; }
        public int? Cip26assoc { get; set; }
        public int? Cip26cert4 { get; set; }
        public int? Cip26bachl { get; set; }
        public int? Cip27cert1 { get; set; }
        public int? Cip27cert2 { get; set; }
        public int? Cip27assoc { get; set; }
        public int? Cip27cert4 { get; set; }
        public int? Cip27bachl { get; set; }
        public int? Cip29cert1 { get; set; }
        public int? Cip29cert2 { get; set; }
        public int? Cip29assoc { get; set; }
        public int? Cip29cert4 { get; set; }
        public int? Cip29bachl { get; set; }
        public int? Cip30cert1 { get; set; }
        public int? Cip30cert2 { get; set; }
        public int? Cip30assoc { get; set; }
        public int? Cip30cert4 { get; set; }
        public int? Cip30bachl { get; set; }
        public int? Cip31cert1 { get; set; }
        public int? Cip31cert2 { get; set; }
        public int? Cip31assoc { get; set; }
        public int? Cip31cert4 { get; set; }
        public int? Cip31bachl { get; set; }
        public int? Cip38cert1 { get; set; }
        public int? Cip38cert2 { get; set; }
        public int? Cip38assoc { get; set; }
        public int? Cip38cert4 { get; set; }
        public int? Cip38bachl { get; set; }
        public int? Cip39cert1 { get; set; }
        public int? Cip39cert2 { get; set; }
        public int? Cip39assoc { get; set; }
        public int? Cip39cert4 { get; set; }
        public int? Cip39bachl { get; set; }
        public int? Cip40cert1 { get; set; }
        public int? Cip40cert2 { get; set; }
        public int? Cip40assoc { get; set; }
        public int? Cip40cert4 { get; set; }
        public int? Cip40bachl { get; set; }
        public int? Cip41cert1 { get; set; }
        public int? Cip41cert2 { get; set; }
        public int? Cip41assoc { get; set; }
        public int? Cip41cert4 { get; set; }
        public int? Cip41bachl { get; set; }
        public int? Cip42cert1 { get; set; }
        public int? Cip42cert2 { get; set; }
        public int? Cip42assoc { get; set; }
        public int? Cip42cert4 { get; set; }
        public int? Cip42bachl { get; set; }
        public int? Cip43cert1 { get; set; }
        public int? Cip43cert2 { get; set; }
        public int? Cip43assoc { get; set; }
        public int? Cip43cert4 { get; set; }
        public int? Cip43bachl { get; set; }
        public int? Cip44cert1 { get; set; }
        public int? Cip44cert2 { get; set; }
        public int? Cip44assoc { get; set; }
        public int? Cip44cert4 { get; set; }
        public int? Cip44bachl { get; set; }
        public int? Cip45cert1 { get; set; }
        public int? Cip45cert2 { get; set; }
        public int? Cip45assoc { get; set; }
        public int? Cip45cert4 { get; set; }
        public int? Cip45bachl { get; set; }
        public int? Cip46cert1 { get; set; }
        public int? Cip46cert2 { get; set; }
        public int? Cip46assoc { get; set; }
        public int? Cip46cert4 { get; set; }
        public int? Cip46bachl { get; set; }
        public int? Cip47cert1 { get; set; }
        public int? Cip47cert2 { get; set; }
        public int? Cip47assoc { get; set; }
        public int? Cip47cert4 { get; set; }
        public int? Cip47bachl { get; set; }
        public int? Cip48cert1 { get; set; }
        public int? Cip48cert2 { get; set; }
        public int? Cip48assoc { get; set; }
        public int? Cip48cert4 { get; set; }
        public int? Cip48bachl { get; set; }
        public int? Cip49cert1 { get; set; }
        public int? Cip49cert2 { get; set; }
        public int? Cip49assoc { get; set; }
        public int? Cip49cert4 { get; set; }
        public int? Cip49bachl { get; set; }
        public int? Cip50cert1 { get; set; }
        public int? Cip50cert2 { get; set; }
        public int? Cip50assoc { get; set; }
        public int? Cip50cert4 { get; set; }
        public int? Cip50bachl { get; set; }
        public int? Cip51cert1 { get; set; }
        public int? Cip51cert2 { get; set; }
        public int? Cip51assoc { get; set; }
        public int? Cip51cert4 { get; set; }
        public int? Cip51bachl { get; set; }
        public int? Cip52cert1 { get; set; }
        public int? Cip52cert2 { get; set; }
        public int? Cip52assoc { get; set; }
        public int? Cip52cert4 { get; set; }
        public int? Cip52bachl { get; set; }
        public int? Cip54cert1 { get; set; }
        public int? Cip54cert2 { get; set; }
        public int? Cip54assoc { get; set; }
        public int? Cip54cert4 { get; set; }
        public int? Cip54bachl { get; set; }

        public virtual Root Unit { get; set; }
    }
}
