using System;
using System.Collections.Generic;

namespace JonasTest.Data.Model
{
    public partial class Completion
    {
        public int Unitid { get; set; }
        public decimal? C1504 { get; set; }
        public decimal? C150L4 { get; set; }
        public decimal? C1504Pooled { get; set; }
        public decimal? C150L4Pooled { get; set; }
        public int? Poolyrs { get; set; }
        public int? D1504 { get; set; }
        public int? D150L4 { get; set; }
        public int? D1504Pooled { get; set; }
        public int? D150L4Pooled { get; set; }
        public decimal? C1504White { get; set; }
        public decimal? C1504Black { get; set; }
        public decimal? C1504Hisp { get; set; }
        public decimal? C1504Asian { get; set; }
        public decimal? C1504Aian { get; set; }
        public decimal? C1504Nhpi { get; set; }
        public decimal? C15042mor { get; set; }
        public decimal? C1504Nra { get; set; }
        public decimal? C1504Unkn { get; set; }
        public decimal? C1504Whitenh { get; set; }
        public decimal? C1504Blacknh { get; set; }
        public decimal? C1504Api { get; set; }
        public decimal? C1504Aianold { get; set; }
        public decimal? C1504Hispold { get; set; }
        public decimal? C150L4White { get; set; }
        public decimal? C150L4Black { get; set; }
        public decimal? C150L4Hisp { get; set; }
        public decimal? C150L4Asian { get; set; }
        public decimal? C150L4Aian { get; set; }
        public decimal? C150L4Nhpi { get; set; }
        public decimal? C150L42mor { get; set; }
        public decimal? C150L4Nra { get; set; }
        public decimal? C150L4Unkn { get; set; }
        public decimal? C150L4Whitenh { get; set; }
        public decimal? C150L4Blacknh { get; set; }
        public decimal? C150L4Api { get; set; }
        public decimal? C150L4Aianold { get; set; }
        public decimal? C150L4Hispold { get; set; }
        public decimal? C2004 { get; set; }
        public decimal? C200L4 { get; set; }
        public decimal? D2004 { get; set; }
        public decimal? D200L4 { get; set; }
        public decimal? C2004Pooled { get; set; }
        public decimal? C200L4Pooled { get; set; }
        public int? Poolyrs200 { get; set; }
        public decimal? D2004Pooled { get; set; }
        public decimal? D200L4Pooled { get; set; }
        public int? OverallYr2N { get; set; }
        public int? LoIncYr2N { get; set; }
        public int? MdIncYr2N { get; set; }
        public int? HiIncYr2N { get; set; }
        public int? DepYr2N { get; set; }
        public int? IndYr2N { get; set; }
        public int? FemaleYr2N { get; set; }
        public int? MaleYr2N { get; set; }
        public int? PellYr2N { get; set; }
        public int? NopellYr2N { get; set; }
        public int? LoanYr2N { get; set; }
        public int? NoloanYr2N { get; set; }
        public int? FirstgenYr2N { get; set; }
        public int? Not1stgenYr2N { get; set; }
        public int? OverallYr3N { get; set; }
        public int? LoIncYr3N { get; set; }
        public int? MdIncYr3N { get; set; }
        public int? HiIncYr3N { get; set; }
        public int? DepYr3N { get; set; }
        public int? IndYr3N { get; set; }
        public int? FemaleYr3N { get; set; }
        public int? MaleYr3N { get; set; }
        public int? PellYr3N { get; set; }
        public int? NopellYr3N { get; set; }
        public int? LoanYr3N { get; set; }
        public int? NoloanYr3N { get; set; }
        public int? FirstgenYr3N { get; set; }
        public int? Not1stgenYr3N { get; set; }
        public int? OverallYr4N { get; set; }
        public int? LoIncYr4N { get; set; }
        public int? MdIncYr4N { get; set; }
        public int? HiIncYr4N { get; set; }
        public int? DepYr4N { get; set; }
        public int? IndYr4N { get; set; }
        public int? FemaleYr4N { get; set; }
        public int? MaleYr4N { get; set; }
        public int? PellYr4N { get; set; }
        public int? NopellYr4N { get; set; }
        public int? LoanYr4N { get; set; }
        public int? NoloanYr4N { get; set; }
        public int? FirstgenYr4N { get; set; }
        public int? Not1stgenYr4N { get; set; }
        public int? OverallYr6N { get; set; }
        public int? LoIncYr6N { get; set; }
        public int? MdIncYr6N { get; set; }
        public int? HiIncYr6N { get; set; }
        public int? DepYr6N { get; set; }
        public int? IndYr6N { get; set; }
        public int? FemaleYr6N { get; set; }
        public int? MaleYr6N { get; set; }
        public int? PellYr6N { get; set; }
        public int? NopellYr6N { get; set; }
        public int? LoanYr6N { get; set; }
        public int? NoloanYr6N { get; set; }
        public int? FirstgenYr6N { get; set; }
        public int? Not1stgenYr6N { get; set; }
        public int? OverallYr8N { get; set; }
        public int? LoIncYr8N { get; set; }
        public int? MdIncYr8N { get; set; }
        public int? HiIncYr8N { get; set; }
        public int? DepYr8N { get; set; }
        public int? IndYr8N { get; set; }
        public int? FemaleYr8N { get; set; }
        public int? MaleYr8N { get; set; }
        public int? PellYr8N { get; set; }
        public int? NopellYr8N { get; set; }
        public int? LoanYr8N { get; set; }
        public int? NoloanYr8N { get; set; }
        public int? FirstgenYr8N { get; set; }
        public int? Not1stgenYr8N { get; set; }
        public string SeparDtMdn { get; set; }
        public int? SeparDtN { get; set; }
        public decimal? C150L4PooledSupp { get; set; }
        public decimal? C1504PooledSupp { get; set; }
        public decimal? C200L4PooledSupp { get; set; }
        public decimal? C2004PooledSupp { get; set; }
        public decimal? C1004 { get; set; }
        public int? D1004 { get; set; }
        public decimal? C100L4 { get; set; }
        public int? D100L4 { get; set; }
        public decimal? Trans4 { get; set; }
        public int? Dtrans4 { get; set; }
        public decimal? TransL4 { get; set; }
        public int? DtransL4 { get; set; }
        public int? D1504White { get; set; }
        public int? D1504Black { get; set; }
        public int? D1504Hisp { get; set; }
        public int? D1504Asian { get; set; }
        public int? D1504Aian { get; set; }
        public int? D1504Nhpi { get; set; }
        public int? D15042mor { get; set; }
        public int? D1504Nra { get; set; }
        public int? D1504Unkn { get; set; }
        public int? D150L4White { get; set; }
        public int? D150L4Black { get; set; }
        public int? D150L4Hisp { get; set; }
        public int? D150L4Asian { get; set; }
        public int? D150L4Aian { get; set; }
        public int? D150L4Nhpi { get; set; }
        public int? D150L42mor { get; set; }
        public int? D150L4Nra { get; set; }
        public int? D150L4Unkn { get; set; }
        public int? D1504Whitenh { get; set; }
        public int? D1504Blacknh { get; set; }
        public int? D1504Api { get; set; }
        public int? D1504Aianold { get; set; }
        public int? D1504Hispold { get; set; }
        public int? D150L4Whitenh { get; set; }
        public int? D150L4Blacknh { get; set; }
        public int? D150L4Api { get; set; }
        public int? D150L4Aianold { get; set; }
        public int? D150L4Hispold { get; set; }
        public int? Omacht6Ftft { get; set; }
        public decimal? Omawdp6Ftft { get; set; }
        public int? Omacht8Ftft { get; set; }
        public decimal? Omawdp8Ftft { get; set; }
        public decimal? Omenryp8Ftft { get; set; }
        public decimal? Omenrap8Ftft { get; set; }
        public decimal? Omenrup8Ftft { get; set; }
        public int? Omacht6Ptft { get; set; }
        public decimal? Omawdp6Ptft { get; set; }
        public int? Omacht8Ptft { get; set; }
        public decimal? Omawdp8Ptft { get; set; }
        public decimal? Omenryp8Ptft { get; set; }
        public decimal? Omenrap8Ptft { get; set; }
        public decimal? Omenrup8Ptft { get; set; }
        public int? Omacht6Ftnft { get; set; }
        public decimal? Omawdp6Ftnft { get; set; }
        public int? Omacht8Ftnft { get; set; }
        public decimal? Omawdp8Ftnft { get; set; }
        public decimal? Omenryp8Ftnft { get; set; }
        public decimal? Omenrap8Ftnft { get; set; }
        public decimal? Omenrup8Ftnft { get; set; }
        public int? Omacht6Ptnft { get; set; }
        public decimal? Omawdp6Ptnft { get; set; }
        public int? Omacht8Ptnft { get; set; }
        public decimal? Omawdp8Ptnft { get; set; }
        public decimal? Omenryp8Ptnft { get; set; }
        public decimal? Omenrap8Ptnft { get; set; }
        public decimal? Omenrup8Ptnft { get; set; }
        public decimal? Trans4Pooled { get; set; }
        public decimal? TransL4Pooled { get; set; }
        public int? Dtrans4Pooled { get; set; }
        public int? DtransL4Pooled { get; set; }
        public decimal? Trans4PooledSupp { get; set; }
        public decimal? TransL4PooledSupp { get; set; }
        public decimal? C1004Pooled { get; set; }
        public decimal? C100L4Pooled { get; set; }
        public int? D1004Pooled { get; set; }
        public int? D100L4Pooled { get; set; }
        public int? Poolyrs100 { get; set; }
        public decimal? C1004PooledSupp { get; set; }
        public decimal? C100L4PooledSupp { get; set; }
        public decimal? C1504Pell { get; set; }
        public int? D1504Pell { get; set; }
        public decimal? C150L4Pell { get; set; }
        public int? D150L4Pell { get; set; }
        public decimal? C1504Loannopell { get; set; }
        public int? D1504Loannopell { get; set; }
        public decimal? C150L4Loannopell { get; set; }
        public int? D150L4Loannopell { get; set; }
        public decimal? C1504Noloannopell { get; set; }
        public int? D1504Noloannopell { get; set; }
        public decimal? C150L4Noloannopell { get; set; }
        public int? D150L4Noloannopell { get; set; }
        public int? Omacht6FtftPooled { get; set; }
        public decimal? Omawdp6FtftPooled { get; set; }
        public int? Omacht8FtftPooled { get; set; }
        public decimal? Omawdp8FtftPooled { get; set; }
        public decimal? Omenryp8FtftPooled { get; set; }
        public decimal? Omenrap8FtftPooled { get; set; }
        public decimal? Omenrup8FtftPooled { get; set; }
        public int? Omacht6PtftPooled { get; set; }
        public decimal? Omawdp6PtftPooled { get; set; }
        public int? Omacht8PtftPooled { get; set; }
        public decimal? Omawdp8PtftPooled { get; set; }
        public decimal? Omenryp8PtftPooled { get; set; }
        public decimal? Omenrap8PtftPooled { get; set; }
        public decimal? Omenrup8PtftPooled { get; set; }
        public int? Omacht6FtnftPooled { get; set; }
        public decimal? Omawdp6FtnftPooled { get; set; }
        public int? Omacht8FtnftPooled { get; set; }
        public decimal? Omawdp8FtnftPooled { get; set; }
        public decimal? Omenryp8FtnftPooled { get; set; }
        public decimal? Omenrap8FtnftPooled { get; set; }
        public decimal? Omenrup8FtnftPooled { get; set; }
        public int? Omacht6PtnftPooled { get; set; }
        public decimal? Omawdp6PtnftPooled { get; set; }
        public int? Omacht8PtnftPooled { get; set; }
        public decimal? Omawdp8PtnftPooled { get; set; }
        public decimal? Omenryp8PtnftPooled { get; set; }
        public decimal? Omenrap8PtnftPooled { get; set; }
        public decimal? Omenrup8PtnftPooled { get; set; }
        public int? PoolyrsOmFtft { get; set; }
        public int? PoolyrsOmPtft { get; set; }
        public int? PoolyrsOmFtnft { get; set; }
        public int? PoolyrsOmPtnft { get; set; }
        public decimal? Omawdp6FtftPooledSupp { get; set; }
        public decimal? Omawdp8FtftPooledSupp { get; set; }
        public decimal? Omenryp8FtftPooledSupp { get; set; }
        public decimal? Omenrap8FtftPooledSupp { get; set; }
        public decimal? Omenrup8FtftPooledSupp { get; set; }
        public decimal? Omawdp6PtftPooledSupp { get; set; }
        public decimal? Omawdp8PtftPooledSupp { get; set; }
        public decimal? Omenryp8PtftPooledSupp { get; set; }
        public decimal? Omenrap8PtftPooledSupp { get; set; }
        public decimal? Omenrup8PtftPooledSupp { get; set; }
        public decimal? Omawdp6FtnftPooledSupp { get; set; }
        public decimal? Omawdp8FtnftPooledSupp { get; set; }
        public decimal? Omenryp8FtnftPooledSupp { get; set; }
        public decimal? Omenrap8FtnftPooledSupp { get; set; }
        public decimal? Omenrup8FtnftPooledSupp { get; set; }
        public decimal? Omawdp6PtnftPooledSupp { get; set; }
        public decimal? Omawdp8PtnftPooledSupp { get; set; }
        public decimal? Omenryp8PtnftPooledSupp { get; set; }
        public decimal? Omenrap8PtnftPooledSupp { get; set; }
        public decimal? Omenrup8PtnftPooledSupp { get; set; }

        public virtual Root Unit { get; set; }
    }
}
