using System;
using System.Collections.Generic;

namespace JonasTest.Data.Model
{
    public partial class Repayment
    {
        public int Unitid { get; set; }
        public decimal? Cdr2 { get; set; }
        public decimal? Cdr3 { get; set; }
        public decimal? Rpy1yrRt { get; set; }
        public decimal? ComplRpy1yrRt { get; set; }
        public decimal? NoncomRpy1yrRt { get; set; }
        public decimal? LoIncRpy1yrRt { get; set; }
        public decimal? MdIncRpy1yrRt { get; set; }
        public decimal? HiIncRpy1yrRt { get; set; }
        public decimal? DepRpy1yrRt { get; set; }
        public decimal? IndRpy1yrRt { get; set; }
        public decimal? PellRpy1yrRt { get; set; }
        public decimal? NopellRpy1yrRt { get; set; }
        public decimal? FemaleRpy1yrRt { get; set; }
        public decimal? MaleRpy1yrRt { get; set; }
        public decimal? FirstgenRpy1yrRt { get; set; }
        public decimal? NotfirstgenRpy1yrRt { get; set; }
        public decimal? Rpy3yrRt { get; set; }
        public decimal? ComplRpy3yrRt { get; set; }
        public decimal? NoncomRpy3yrRt { get; set; }
        public decimal? LoIncRpy3yrRt { get; set; }
        public decimal? MdIncRpy3yrRt { get; set; }
        public decimal? HiIncRpy3yrRt { get; set; }
        public decimal? DepRpy3yrRt { get; set; }
        public decimal? IndRpy3yrRt { get; set; }
        public decimal? PellRpy3yrRt { get; set; }
        public decimal? NopellRpy3yrRt { get; set; }
        public decimal? FemaleRpy3yrRt { get; set; }
        public decimal? MaleRpy3yrRt { get; set; }
        public decimal? FirstgenRpy3yrRt { get; set; }
        public decimal? NotfirstgenRpy3yrRt { get; set; }
        public decimal? Rpy5yrRt { get; set; }
        public decimal? ComplRpy5yrRt { get; set; }
        public decimal? NoncomRpy5yrRt { get; set; }
        public decimal? LoIncRpy5yrRt { get; set; }
        public decimal? MdIncRpy5yrRt { get; set; }
        public decimal? HiIncRpy5yrRt { get; set; }
        public decimal? DepRpy5yrRt { get; set; }
        public decimal? IndRpy5yrRt { get; set; }
        public decimal? PellRpy5yrRt { get; set; }
        public decimal? NopellRpy5yrRt { get; set; }
        public decimal? FemaleRpy5yrRt { get; set; }
        public decimal? MaleRpy5yrRt { get; set; }
        public decimal? FirstgenRpy5yrRt { get; set; }
        public decimal? NotfirstgenRpy5yrRt { get; set; }
        public decimal? Rpy7yrRt { get; set; }
        public decimal? ComplRpy7yrRt { get; set; }
        public decimal? NoncomRpy7yrRt { get; set; }
        public decimal? LoIncRpy7yrRt { get; set; }
        public decimal? MdIncRpy7yrRt { get; set; }
        public decimal? HiIncRpy7yrRt { get; set; }
        public decimal? DepRpy7yrRt { get; set; }
        public decimal? IndRpy7yrRt { get; set; }
        public decimal? PellRpy7yrRt { get; set; }
        public decimal? NopellRpy7yrRt { get; set; }
        public decimal? FemaleRpy7yrRt { get; set; }
        public decimal? MaleRpy7yrRt { get; set; }
        public decimal? FirstgenRpy7yrRt { get; set; }
        public decimal? NotfirstgenRpy7yrRt { get; set; }
        public string RepayDtMdn { get; set; }
        public int? RepayDtN { get; set; }
        public int? Rpy1yrN { get; set; }
        public int? ComplRpy1yrN { get; set; }
        public int? NoncomRpy1yrN { get; set; }
        public int? LoIncRpy1yrN { get; set; }
        public int? MdIncRpy1yrN { get; set; }
        public int? HiIncRpy1yrN { get; set; }
        public int? DepRpy1yrN { get; set; }
        public int? IndRpy1yrN { get; set; }
        public int? PellRpy1yrN { get; set; }
        public int? NopellRpy1yrN { get; set; }
        public int? FemaleRpy1yrN { get; set; }
        public int? MaleRpy1yrN { get; set; }
        public int? FirstgenRpy1yrN { get; set; }
        public int? NotfirstgenRpy1yrN { get; set; }
        public int? Rpy3yrN { get; set; }
        public int? ComplRpy3yrN { get; set; }
        public int? NoncomRpy3yrN { get; set; }
        public int? LoIncRpy3yrN { get; set; }
        public int? MdIncRpy3yrN { get; set; }
        public int? HiIncRpy3yrN { get; set; }
        public int? DepRpy3yrN { get; set; }
        public int? IndRpy3yrN { get; set; }
        public int? PellRpy3yrN { get; set; }
        public int? NopellRpy3yrN { get; set; }
        public int? FemaleRpy3yrN { get; set; }
        public int? MaleRpy3yrN { get; set; }
        public int? FirstgenRpy3yrN { get; set; }
        public int? NotfirstgenRpy3yrN { get; set; }
        public int? Rpy5yrN { get; set; }
        public int? ComplRpy5yrN { get; set; }
        public int? NoncomRpy5yrN { get; set; }
        public int? LoIncRpy5yrN { get; set; }
        public int? MdIncRpy5yrN { get; set; }
        public int? HiIncRpy5yrN { get; set; }
        public int? DepRpy5yrN { get; set; }
        public int? IndRpy5yrN { get; set; }
        public int? PellRpy5yrN { get; set; }
        public int? NopellRpy5yrN { get; set; }
        public int? FemaleRpy5yrN { get; set; }
        public int? MaleRpy5yrN { get; set; }
        public int? FirstgenRpy5yrN { get; set; }
        public int? NotfirstgenRpy5yrN { get; set; }
        public int? Rpy7yrN { get; set; }
        public int? ComplRpy7yrN { get; set; }
        public int? NoncomRpy7yrN { get; set; }
        public int? LoIncRpy7yrN { get; set; }
        public int? MdIncRpy7yrN { get; set; }
        public int? HiIncRpy7yrN { get; set; }
        public int? DepRpy7yrN { get; set; }
        public int? IndRpy7yrN { get; set; }
        public int? PellRpy7yrN { get; set; }
        public int? NopellRpy7yrN { get; set; }
        public int? FemaleRpy7yrN { get; set; }
        public int? MaleRpy7yrN { get; set; }
        public int? FirstgenRpy7yrN { get; set; }
        public int? NotfirstgenRpy7yrN { get; set; }
        public decimal? Rpy3yrRtSupp { get; set; }
        public decimal? LoIncRpy3yrRtSupp { get; set; }
        public decimal? MdIncRpy3yrRtSupp { get; set; }
        public decimal? HiIncRpy3yrRtSupp { get; set; }
        public decimal? ComplRpy3yrRtSupp { get; set; }
        public decimal? NoncomRpy3yrRtSupp { get; set; }
        public decimal? DepRpy3yrRtSupp { get; set; }
        public decimal? IndRpy3yrRtSupp { get; set; }
        public decimal? PellRpy3yrRtSupp { get; set; }
        public decimal? NopellRpy3yrRtSupp { get; set; }
        public decimal? FemaleRpy3yrRtSupp { get; set; }
        public decimal? MaleRpy3yrRtSupp { get; set; }
        public decimal? FirstgenRpy3yrRtSupp { get; set; }
        public decimal? NotfirstgenRpy3yrRtSupp { get; set; }
        public int? Cdr2Denom { get; set; }
        public int? Cdr3Denom { get; set; }

        public virtual Root Unit { get; set; }
    }
}
