using System;
using System.Collections.Generic;

namespace JonasTest.Data.Model
{
    public partial class TitleIv
    {
        public int Unitid { get; set; }
        public decimal? DeathYr2Rt { get; set; }
        public decimal? CompOrigYr2Rt { get; set; }
        public decimal? Comp4yrTransYr2Rt { get; set; }
        public decimal? Comp2yrTransYr2Rt { get; set; }
        public decimal? WdrawOrigYr2Rt { get; set; }
        public decimal? Wdraw4yrTransYr2Rt { get; set; }
        public decimal? Wdraw2yrTransYr2Rt { get; set; }
        public decimal? EnrlOrigYr2Rt { get; set; }
        public decimal? Enrl4yrTransYr2Rt { get; set; }
        public decimal? Enrl2yrTransYr2Rt { get; set; }
        public decimal? UnknOrigYr2Rt { get; set; }
        public decimal? Unkn4yrTransYr2Rt { get; set; }
        public decimal? Unkn2yrTransYr2Rt { get; set; }
        public decimal? LoIncDeathYr2Rt { get; set; }
        public decimal? LoIncCompOrigYr2Rt { get; set; }
        public decimal? LoIncComp4yrTransYr2Rt { get; set; }
        public decimal? LoIncComp2yrTransYr2Rt { get; set; }
        public decimal? LoIncWdrawOrigYr2Rt { get; set; }
        public decimal? LoIncWdraw4yrTransYr2Rt { get; set; }
        public decimal? LoIncWdraw2yrTransYr2Rt { get; set; }
        public decimal? LoIncEnrlOrigYr2Rt { get; set; }
        public decimal? LoIncEnrl4yrTransYr2Rt { get; set; }
        public decimal? LoIncEnrl2yrTransYr2Rt { get; set; }
        public decimal? LoIncUnknOrigYr2Rt { get; set; }
        public decimal? LoIncUnkn4yrTransYr2Rt { get; set; }
        public decimal? LoIncUnkn2yrTransYr2Rt { get; set; }
        public decimal? MdIncDeathYr2Rt { get; set; }
        public decimal? MdIncCompOrigYr2Rt { get; set; }
        public decimal? MdIncComp4yrTransYr2Rt { get; set; }
        public decimal? MdIncComp2yrTransYr2Rt { get; set; }
        public decimal? MdIncWdrawOrigYr2Rt { get; set; }
        public decimal? MdIncWdraw4yrTransYr2Rt { get; set; }
        public decimal? MdIncWdraw2yrTransYr2Rt { get; set; }
        public decimal? MdIncEnrlOrigYr2Rt { get; set; }
        public decimal? MdIncEnrl4yrTransYr2Rt { get; set; }
        public decimal? MdIncEnrl2yrTransYr2Rt { get; set; }
        public decimal? MdIncUnknOrigYr2Rt { get; set; }
        public decimal? MdIncUnkn4yrTransYr2Rt { get; set; }
        public decimal? MdIncUnkn2yrTransYr2Rt { get; set; }
        public decimal? HiIncDeathYr2Rt { get; set; }
        public decimal? HiIncCompOrigYr2Rt { get; set; }
        public decimal? HiIncComp4yrTransYr2Rt { get; set; }
        public decimal? HiIncComp2yrTransYr2Rt { get; set; }
        public decimal? HiIncWdrawOrigYr2Rt { get; set; }
        public decimal? HiIncWdraw4yrTransYr2Rt { get; set; }
        public decimal? HiIncWdraw2yrTransYr2Rt { get; set; }
        public decimal? HiIncEnrlOrigYr2Rt { get; set; }
        public decimal? HiIncEnrl4yrTransYr2Rt { get; set; }
        public decimal? HiIncEnrl2yrTransYr2Rt { get; set; }
        public decimal? HiIncUnknOrigYr2Rt { get; set; }
        public decimal? HiIncUnkn4yrTransYr2Rt { get; set; }
        public decimal? HiIncUnkn2yrTransYr2Rt { get; set; }
        public decimal? DepDeathYr2Rt { get; set; }
        public decimal? DepCompOrigYr2Rt { get; set; }
        public decimal? DepComp4yrTransYr2Rt { get; set; }
        public decimal? DepComp2yrTransYr2Rt { get; set; }
        public decimal? DepWdrawOrigYr2Rt { get; set; }
        public decimal? DepWdraw4yrTransYr2Rt { get; set; }
        public decimal? DepWdraw2yrTransYr2Rt { get; set; }
        public decimal? DepEnrlOrigYr2Rt { get; set; }
        public decimal? DepEnrl4yrTransYr2Rt { get; set; }
        public decimal? DepEnrl2yrTransYr2Rt { get; set; }
        public decimal? DepUnknOrigYr2Rt { get; set; }
        public decimal? DepUnkn4yrTransYr2Rt { get; set; }
        public decimal? DepUnkn2yrTransYr2Rt { get; set; }
        public decimal? IndDeathYr2Rt { get; set; }
        public decimal? IndCompOrigYr2Rt { get; set; }
        public decimal? IndComp4yrTransYr2Rt { get; set; }
        public decimal? IndComp2yrTransYr2Rt { get; set; }
        public decimal? IndWdrawOrigYr2Rt { get; set; }
        public decimal? IndWdraw4yrTransYr2Rt { get; set; }
        public decimal? IndWdraw2yrTransYr2Rt { get; set; }
        public decimal? IndEnrlOrigYr2Rt { get; set; }
        public decimal? IndEnrl4yrTransYr2Rt { get; set; }
        public decimal? IndEnrl2yrTransYr2Rt { get; set; }
        public decimal? IndUnknOrigYr2Rt { get; set; }
        public decimal? IndUnkn4yrTransYr2Rt { get; set; }
        public decimal? IndUnkn2yrTransYr2Rt { get; set; }
        public decimal? FemaleDeathYr2Rt { get; set; }
        public decimal? FemaleCompOrigYr2Rt { get; set; }
        public decimal? FemaleComp4yrTransYr2Rt { get; set; }
        public decimal? FemaleComp2yrTransYr2Rt { get; set; }
        public decimal? FemaleWdrawOrigYr2Rt { get; set; }
        public decimal? FemaleWdraw4yrTransYr2Rt { get; set; }
        public decimal? FemaleWdraw2yrTransYr2Rt { get; set; }
        public decimal? FemaleEnrlOrigYr2Rt { get; set; }
        public decimal? FemaleEnrl4yrTransYr2Rt { get; set; }
        public decimal? FemaleEnrl2yrTransYr2Rt { get; set; }
        public decimal? FemaleUnknOrigYr2Rt { get; set; }
        public decimal? FemaleUnkn4yrTransYr2Rt { get; set; }
        public decimal? FemaleUnkn2yrTransYr2Rt { get; set; }
        public decimal? MaleDeathYr2Rt { get; set; }
        public decimal? MaleCompOrigYr2Rt { get; set; }
        public decimal? MaleComp4yrTransYr2Rt { get; set; }
        public decimal? MaleComp2yrTransYr2Rt { get; set; }
        public decimal? MaleWdrawOrigYr2Rt { get; set; }
        public decimal? MaleWdraw4yrTransYr2Rt { get; set; }
        public decimal? MaleWdraw2yrTransYr2Rt { get; set; }
        public decimal? MaleEnrlOrigYr2Rt { get; set; }
        public decimal? MaleEnrl4yrTransYr2Rt { get; set; }
        public decimal? MaleEnrl2yrTransYr2Rt { get; set; }
        public decimal? MaleUnknOrigYr2Rt { get; set; }
        public decimal? MaleUnkn4yrTransYr2Rt { get; set; }
        public decimal? MaleUnkn2yrTransYr2Rt { get; set; }
        public decimal? PellDeathYr2Rt { get; set; }
        public decimal? PellCompOrigYr2Rt { get; set; }
        public decimal? PellComp4yrTransYr2Rt { get; set; }
        public decimal? PellComp2yrTransYr2Rt { get; set; }
        public decimal? PellWdrawOrigYr2Rt { get; set; }
        public decimal? PellWdraw4yrTransYr2Rt { get; set; }
        public decimal? PellWdraw2yrTransYr2Rt { get; set; }
        public decimal? PellEnrlOrigYr2Rt { get; set; }
        public decimal? PellEnrl4yrTransYr2Rt { get; set; }
        public decimal? PellEnrl2yrTransYr2Rt { get; set; }
        public decimal? PellUnknOrigYr2Rt { get; set; }
        public decimal? PellUnkn4yrTransYr2Rt { get; set; }
        public decimal? PellUnkn2yrTransYr2Rt { get; set; }
        public decimal? NopellDeathYr2Rt { get; set; }
        public decimal? NopellCompOrigYr2Rt { get; set; }
        public decimal? NopellComp4yrTransYr2Rt { get; set; }
        public decimal? NopellComp2yrTransYr2Rt { get; set; }
        public decimal? NopellWdrawOrigYr2Rt { get; set; }
        public decimal? NopellWdraw4yrTransYr2Rt { get; set; }
        public decimal? NopellWdraw2yrTransYr2Rt { get; set; }
        public decimal? NopellEnrlOrigYr2Rt { get; set; }
        public decimal? NopellEnrl4yrTransYr2Rt { get; set; }
        public decimal? NopellEnrl2yrTransYr2Rt { get; set; }
        public decimal? NopellUnknOrigYr2Rt { get; set; }
        public decimal? NopellUnkn4yrTransYr2Rt { get; set; }
        public decimal? NopellUnkn2yrTransYr2Rt { get; set; }
        public decimal? LoanDeathYr2Rt { get; set; }
        public decimal? LoanCompOrigYr2Rt { get; set; }
        public decimal? LoanComp4yrTransYr2Rt { get; set; }
        public decimal? LoanComp2yrTransYr2Rt { get; set; }
        public decimal? LoanWdrawOrigYr2Rt { get; set; }
        public decimal? LoanWdraw4yrTransYr2Rt { get; set; }
        public decimal? LoanWdraw2yrTransYr2Rt { get; set; }
        public decimal? LoanEnrlOrigYr2Rt { get; set; }
        public decimal? LoanEnrl4yrTransYr2Rt { get; set; }
        public decimal? LoanEnrl2yrTransYr2Rt { get; set; }
        public decimal? LoanUnknOrigYr2Rt { get; set; }
        public decimal? LoanUnkn4yrTransYr2Rt { get; set; }
        public decimal? LoanUnkn2yrTransYr2Rt { get; set; }
        public decimal? NoloanDeathYr2Rt { get; set; }
        public decimal? NoloanCompOrigYr2Rt { get; set; }
        public decimal? NoloanComp4yrTransYr2Rt { get; set; }
        public decimal? NoloanComp2yrTransYr2Rt { get; set; }
        public decimal? NoloanWdrawOrigYr2Rt { get; set; }
        public decimal? NoloanWdraw4yrTransYr2Rt { get; set; }
        public decimal? NoloanWdraw2yrTransYr2Rt { get; set; }
        public decimal? NoloanEnrlOrigYr2Rt { get; set; }
        public decimal? NoloanEnrl4yrTransYr2Rt { get; set; }
        public decimal? NoloanEnrl2yrTransYr2Rt { get; set; }
        public decimal? NoloanUnknOrigYr2Rt { get; set; }
        public decimal? NoloanUnkn4yrTransYr2Rt { get; set; }
        public decimal? NoloanUnkn2yrTransYr2Rt { get; set; }
        public decimal? FirstgenDeathYr2Rt { get; set; }
        public decimal? FirstgenCompOrigYr2Rt { get; set; }
        public decimal? FirstgenComp4yrTransYr2Rt { get; set; }
        public decimal? FirstgenComp2yrTransYr2Rt { get; set; }
        public decimal? FirstgenWdrawOrigYr2Rt { get; set; }
        public decimal? FirstgenWdraw4yrTransYr2Rt { get; set; }
        public decimal? FirstgenWdraw2yrTransYr2Rt { get; set; }
        public decimal? FirstgenEnrlOrigYr2Rt { get; set; }
        public decimal? FirstgenEnrl4yrTransYr2Rt { get; set; }
        public decimal? FirstgenEnrl2yrTransYr2Rt { get; set; }
        public decimal? FirstgenUnknOrigYr2Rt { get; set; }
        public decimal? FirstgenUnkn4yrTransYr2Rt { get; set; }
        public decimal? FirstgenUnkn2yrTransYr2Rt { get; set; }
        public decimal? Not1stgenDeathYr2Rt { get; set; }
        public decimal? Not1stgenCompOrigYr2Rt { get; set; }
        public decimal? Not1stgenComp4yrTransYr2Rt { get; set; }
        public decimal? Not1stgenComp2yrTransYr2Rt { get; set; }
        public decimal? Not1stgenWdrawOrigYr2Rt { get; set; }
        public decimal? Not1stgenWdraw4yrTransYr2Rt { get; set; }
        public decimal? Not1stgenWdraw2yrTransYr2Rt { get; set; }
        public decimal? Not1stgenEnrlOrigYr2Rt { get; set; }
        public decimal? Not1stgenEnrl4yrTransYr2Rt { get; set; }
        public decimal? Not1stgenEnrl2yrTransYr2Rt { get; set; }
        public decimal? Not1stgenUnknOrigYr2Rt { get; set; }
        public decimal? Not1stgenUnkn4yrTransYr2Rt { get; set; }
        public decimal? Not1stgenUnkn2yrTransYr2Rt { get; set; }
        public decimal? DeathYr3Rt { get; set; }
        public decimal? CompOrigYr3Rt { get; set; }
        public decimal? Comp4yrTransYr3Rt { get; set; }
        public decimal? Comp2yrTransYr3Rt { get; set; }
        public decimal? WdrawOrigYr3Rt { get; set; }
        public decimal? Wdraw4yrTransYr3Rt { get; set; }
        public decimal? Wdraw2yrTransYr3Rt { get; set; }
        public decimal? EnrlOrigYr3Rt { get; set; }
        public decimal? Enrl4yrTransYr3Rt { get; set; }
        public decimal? Enrl2yrTransYr3Rt { get; set; }
        public decimal? UnknOrigYr3Rt { get; set; }
        public decimal? Unkn4yrTransYr3Rt { get; set; }
        public decimal? Unkn2yrTransYr3Rt { get; set; }
        public decimal? LoIncDeathYr3Rt { get; set; }
        public decimal? LoIncCompOrigYr3Rt { get; set; }
        public decimal? LoIncComp4yrTransYr3Rt { get; set; }
        public decimal? LoIncComp2yrTransYr3Rt { get; set; }
        public decimal? LoIncWdrawOrigYr3Rt { get; set; }
        public decimal? LoIncWdraw4yrTransYr3Rt { get; set; }
        public decimal? LoIncWdraw2yrTransYr3Rt { get; set; }
        public decimal? LoIncEnrlOrigYr3Rt { get; set; }
        public decimal? LoIncEnrl4yrTransYr3Rt { get; set; }
        public decimal? LoIncEnrl2yrTransYr3Rt { get; set; }
        public decimal? LoIncUnknOrigYr3Rt { get; set; }
        public decimal? LoIncUnkn4yrTransYr3Rt { get; set; }
        public decimal? LoIncUnkn2yrTransYr3Rt { get; set; }
        public decimal? MdIncDeathYr3Rt { get; set; }
        public decimal? MdIncCompOrigYr3Rt { get; set; }
        public decimal? MdIncComp4yrTransYr3Rt { get; set; }
        public decimal? MdIncComp2yrTransYr3Rt { get; set; }
        public decimal? MdIncWdrawOrigYr3Rt { get; set; }
        public decimal? MdIncWdraw4yrTransYr3Rt { get; set; }
        public decimal? MdIncWdraw2yrTransYr3Rt { get; set; }
        public decimal? MdIncEnrlOrigYr3Rt { get; set; }
        public decimal? MdIncEnrl4yrTransYr3Rt { get; set; }
        public decimal? MdIncEnrl2yrTransYr3Rt { get; set; }
        public decimal? MdIncUnknOrigYr3Rt { get; set; }
        public decimal? MdIncUnkn4yrTransYr3Rt { get; set; }
        public decimal? MdIncUnkn2yrTransYr3Rt { get; set; }
        public decimal? HiIncDeathYr3Rt { get; set; }
        public decimal? HiIncCompOrigYr3Rt { get; set; }
        public decimal? HiIncComp4yrTransYr3Rt { get; set; }
        public decimal? HiIncComp2yrTransYr3Rt { get; set; }
        public decimal? HiIncWdrawOrigYr3Rt { get; set; }
        public decimal? HiIncWdraw4yrTransYr3Rt { get; set; }
        public decimal? HiIncWdraw2yrTransYr3Rt { get; set; }
        public decimal? HiIncEnrlOrigYr3Rt { get; set; }
        public decimal? HiIncEnrl4yrTransYr3Rt { get; set; }
        public decimal? HiIncEnrl2yrTransYr3Rt { get; set; }
        public decimal? HiIncUnknOrigYr3Rt { get; set; }
        public decimal? HiIncUnkn4yrTransYr3Rt { get; set; }
        public decimal? HiIncUnkn2yrTransYr3Rt { get; set; }
        public decimal? DepDeathYr3Rt { get; set; }
        public decimal? DepCompOrigYr3Rt { get; set; }
        public decimal? DepComp4yrTransYr3Rt { get; set; }
        public decimal? DepComp2yrTransYr3Rt { get; set; }
        public decimal? DepWdrawOrigYr3Rt { get; set; }
        public decimal? DepWdraw4yrTransYr3Rt { get; set; }
        public decimal? DepWdraw2yrTransYr3Rt { get; set; }
        public decimal? DepEnrlOrigYr3Rt { get; set; }
        public decimal? DepEnrl4yrTransYr3Rt { get; set; }
        public decimal? DepEnrl2yrTransYr3Rt { get; set; }
        public decimal? DepUnknOrigYr3Rt { get; set; }
        public decimal? DepUnkn4yrTransYr3Rt { get; set; }
        public decimal? DepUnkn2yrTransYr3Rt { get; set; }
        public decimal? IndDeathYr3Rt { get; set; }
        public decimal? IndCompOrigYr3Rt { get; set; }
        public decimal? IndComp4yrTransYr3Rt { get; set; }
        public decimal? IndComp2yrTransYr3Rt { get; set; }
        public decimal? IndWdrawOrigYr3Rt { get; set; }
        public decimal? IndWdraw4yrTransYr3Rt { get; set; }
        public decimal? IndWdraw2yrTransYr3Rt { get; set; }
        public decimal? IndEnrlOrigYr3Rt { get; set; }
        public decimal? IndEnrl4yrTransYr3Rt { get; set; }
        public decimal? IndEnrl2yrTransYr3Rt { get; set; }
        public decimal? IndUnknOrigYr3Rt { get; set; }
        public decimal? IndUnkn4yrTransYr3Rt { get; set; }
        public decimal? IndUnkn2yrTransYr3Rt { get; set; }
        public decimal? FemaleDeathYr3Rt { get; set; }
        public decimal? FemaleCompOrigYr3Rt { get; set; }
        public decimal? FemaleComp4yrTransYr3Rt { get; set; }
        public decimal? FemaleComp2yrTransYr3Rt { get; set; }
        public decimal? FemaleWdrawOrigYr3Rt { get; set; }
        public decimal? FemaleWdraw4yrTransYr3Rt { get; set; }
        public decimal? FemaleWdraw2yrTransYr3Rt { get; set; }
        public decimal? FemaleEnrlOrigYr3Rt { get; set; }
        public decimal? FemaleEnrl4yrTransYr3Rt { get; set; }
        public decimal? FemaleEnrl2yrTransYr3Rt { get; set; }
        public decimal? FemaleUnknOrigYr3Rt { get; set; }
        public decimal? FemaleUnkn4yrTransYr3Rt { get; set; }
        public decimal? FemaleUnkn2yrTransYr3Rt { get; set; }
        public decimal? MaleDeathYr3Rt { get; set; }
        public decimal? MaleCompOrigYr3Rt { get; set; }
        public decimal? MaleComp4yrTransYr3Rt { get; set; }
        public decimal? MaleComp2yrTransYr3Rt { get; set; }
        public decimal? MaleWdrawOrigYr3Rt { get; set; }
        public decimal? MaleWdraw4yrTransYr3Rt { get; set; }
        public decimal? MaleWdraw2yrTransYr3Rt { get; set; }
        public decimal? MaleEnrlOrigYr3Rt { get; set; }
        public decimal? MaleEnrl4yrTransYr3Rt { get; set; }
        public decimal? MaleEnrl2yrTransYr3Rt { get; set; }
        public decimal? MaleUnknOrigYr3Rt { get; set; }
        public decimal? MaleUnkn4yrTransYr3Rt { get; set; }
        public decimal? MaleUnkn2yrTransYr3Rt { get; set; }
        public decimal? PellDeathYr3Rt { get; set; }
        public decimal? PellCompOrigYr3Rt { get; set; }
        public decimal? PellComp4yrTransYr3Rt { get; set; }
        public decimal? PellComp2yrTransYr3Rt { get; set; }
        public decimal? PellWdrawOrigYr3Rt { get; set; }
        public decimal? PellWdraw4yrTransYr3Rt { get; set; }
        public decimal? PellWdraw2yrTransYr3Rt { get; set; }
        public decimal? PellEnrlOrigYr3Rt { get; set; }
        public decimal? PellEnrl4yrTransYr3Rt { get; set; }
        public decimal? PellEnrl2yrTransYr3Rt { get; set; }
        public decimal? PellUnknOrigYr3Rt { get; set; }
        public decimal? PellUnkn4yrTransYr3Rt { get; set; }
        public decimal? PellUnkn2yrTransYr3Rt { get; set; }
        public decimal? NopellDeathYr3Rt { get; set; }
        public decimal? NopellCompOrigYr3Rt { get; set; }
        public decimal? NopellComp4yrTransYr3Rt { get; set; }
        public decimal? NopellComp2yrTransYr3Rt { get; set; }
        public decimal? NopellWdrawOrigYr3Rt { get; set; }
        public decimal? NopellWdraw4yrTransYr3Rt { get; set; }
        public decimal? NopellWdraw2yrTransYr3Rt { get; set; }
        public decimal? NopellEnrlOrigYr3Rt { get; set; }
        public decimal? NopellEnrl4yrTransYr3Rt { get; set; }
        public decimal? NopellEnrl2yrTransYr3Rt { get; set; }
        public decimal? NopellUnknOrigYr3Rt { get; set; }
        public decimal? NopellUnkn4yrTransYr3Rt { get; set; }
        public decimal? NopellUnkn2yrTransYr3Rt { get; set; }
        public decimal? LoanDeathYr3Rt { get; set; }
        public decimal? LoanCompOrigYr3Rt { get; set; }
        public decimal? LoanComp4yrTransYr3Rt { get; set; }
        public decimal? LoanComp2yrTransYr3Rt { get; set; }
        public decimal? LoanWdrawOrigYr3Rt { get; set; }
        public decimal? LoanWdraw4yrTransYr3Rt { get; set; }
        public decimal? LoanWdraw2yrTransYr3Rt { get; set; }
        public decimal? LoanEnrlOrigYr3Rt { get; set; }
        public decimal? LoanEnrl4yrTransYr3Rt { get; set; }
        public decimal? LoanEnrl2yrTransYr3Rt { get; set; }
        public decimal? LoanUnknOrigYr3Rt { get; set; }
        public decimal? LoanUnkn4yrTransYr3Rt { get; set; }
        public decimal? LoanUnkn2yrTransYr3Rt { get; set; }
        public decimal? NoloanDeathYr3Rt { get; set; }
        public decimal? NoloanCompOrigYr3Rt { get; set; }
        public decimal? NoloanComp4yrTransYr3Rt { get; set; }
        public decimal? NoloanComp2yrTransYr3Rt { get; set; }
        public decimal? NoloanWdrawOrigYr3Rt { get; set; }
        public decimal? NoloanWdraw4yrTransYr3Rt { get; set; }
        public decimal? NoloanWdraw2yrTransYr3Rt { get; set; }
        public decimal? NoloanEnrlOrigYr3Rt { get; set; }
        public decimal? NoloanEnrl4yrTransYr3Rt { get; set; }
        public decimal? NoloanEnrl2yrTransYr3Rt { get; set; }
        public decimal? NoloanUnknOrigYr3Rt { get; set; }
        public decimal? NoloanUnkn4yrTransYr3Rt { get; set; }
        public decimal? NoloanUnkn2yrTransYr3Rt { get; set; }
        public decimal? FirstgenDeathYr3Rt { get; set; }
        public decimal? FirstgenCompOrigYr3Rt { get; set; }
        public decimal? FirstgenComp4yrTransYr3Rt { get; set; }
        public decimal? FirstgenComp2yrTransYr3Rt { get; set; }
        public decimal? FirstgenWdrawOrigYr3Rt { get; set; }
        public decimal? FirstgenWdraw4yrTransYr3Rt { get; set; }
        public decimal? FirstgenWdraw2yrTransYr3Rt { get; set; }
        public decimal? FirstgenEnrlOrigYr3Rt { get; set; }
        public decimal? FirstgenEnrl4yrTransYr3Rt { get; set; }
        public decimal? FirstgenEnrl2yrTransYr3Rt { get; set; }
        public decimal? FirstgenUnknOrigYr3Rt { get; set; }
        public decimal? FirstgenUnkn4yrTransYr3Rt { get; set; }
        public decimal? FirstgenUnkn2yrTransYr3Rt { get; set; }
        public decimal? Not1stgenDeathYr3Rt { get; set; }
        public decimal? Not1stgenCompOrigYr3Rt { get; set; }
        public decimal? Not1stgenComp4yrTransYr3Rt { get; set; }
        public decimal? Not1stgenComp2yrTransYr3Rt { get; set; }
        public decimal? Not1stgenWdrawOrigYr3Rt { get; set; }
        public decimal? Not1stgenWdraw4yrTransYr3Rt { get; set; }
        public decimal? Not1stgenWdraw2yrTransYr3Rt { get; set; }
        public decimal? Not1stgenEnrlOrigYr3Rt { get; set; }
        public decimal? Not1stgenEnrl4yrTransYr3Rt { get; set; }
        public decimal? Not1stgenEnrl2yrTransYr3Rt { get; set; }
        public decimal? Not1stgenUnknOrigYr3Rt { get; set; }
        public decimal? Not1stgenUnkn4yrTransYr3Rt { get; set; }
        public decimal? Not1stgenUnkn2yrTransYr3Rt { get; set; }
        public decimal? DeathYr4Rt { get; set; }
        public decimal? CompOrigYr4Rt { get; set; }
        public decimal? Comp4yrTransYr4Rt { get; set; }
        public decimal? Comp2yrTransYr4Rt { get; set; }
        public decimal? WdrawOrigYr4Rt { get; set; }
        public decimal? Wdraw4yrTransYr4Rt { get; set; }
        public decimal? Wdraw2yrTransYr4Rt { get; set; }
        public decimal? EnrlOrigYr4Rt { get; set; }
        public decimal? Enrl4yrTransYr4Rt { get; set; }
        public decimal? Enrl2yrTransYr4Rt { get; set; }
        public decimal? UnknOrigYr4Rt { get; set; }
        public decimal? Unkn4yrTransYr4Rt { get; set; }
        public decimal? Unkn2yrTransYr4Rt { get; set; }
        public decimal? LoIncDeathYr4Rt { get; set; }
        public decimal? LoIncCompOrigYr4Rt { get; set; }
        public decimal? LoIncComp4yrTransYr4Rt { get; set; }
        public decimal? LoIncComp2yrTransYr4Rt { get; set; }
        public decimal? LoIncWdrawOrigYr4Rt { get; set; }
        public decimal? LoIncWdraw4yrTransYr4Rt { get; set; }
        public decimal? LoIncWdraw2yrTransYr4Rt { get; set; }
        public decimal? LoIncEnrlOrigYr4Rt { get; set; }
        public decimal? LoIncEnrl4yrTransYr4Rt { get; set; }
        public decimal? LoIncEnrl2yrTransYr4Rt { get; set; }
        public decimal? LoIncUnknOrigYr4Rt { get; set; }
        public decimal? LoIncUnkn4yrTransYr4Rt { get; set; }
        public decimal? LoIncUnkn2yrTransYr4Rt { get; set; }
        public decimal? MdIncDeathYr4Rt { get; set; }
        public decimal? MdIncCompOrigYr4Rt { get; set; }
        public decimal? MdIncComp4yrTransYr4Rt { get; set; }
        public decimal? MdIncComp2yrTransYr4Rt { get; set; }
        public decimal? MdIncWdrawOrigYr4Rt { get; set; }
        public decimal? MdIncWdraw4yrTransYr4Rt { get; set; }
        public decimal? MdIncWdraw2yrTransYr4Rt { get; set; }
        public decimal? MdIncEnrlOrigYr4Rt { get; set; }
        public decimal? MdIncEnrl4yrTransYr4Rt { get; set; }
        public decimal? MdIncEnrl2yrTransYr4Rt { get; set; }
        public decimal? MdIncUnknOrigYr4Rt { get; set; }
        public decimal? MdIncUnkn4yrTransYr4Rt { get; set; }
        public decimal? MdIncUnkn2yrTransYr4Rt { get; set; }
        public decimal? HiIncDeathYr4Rt { get; set; }
        public decimal? HiIncCompOrigYr4Rt { get; set; }
        public decimal? HiIncComp4yrTransYr4Rt { get; set; }
        public decimal? HiIncComp2yrTransYr4Rt { get; set; }
        public decimal? HiIncWdrawOrigYr4Rt { get; set; }
        public decimal? HiIncWdraw4yrTransYr4Rt { get; set; }
        public decimal? HiIncWdraw2yrTransYr4Rt { get; set; }
        public decimal? HiIncEnrlOrigYr4Rt { get; set; }
        public decimal? HiIncEnrl4yrTransYr4Rt { get; set; }
        public decimal? HiIncEnrl2yrTransYr4Rt { get; set; }
        public decimal? HiIncUnknOrigYr4Rt { get; set; }
        public decimal? HiIncUnkn4yrTransYr4Rt { get; set; }
        public decimal? HiIncUnkn2yrTransYr4Rt { get; set; }
        public decimal? DepDeathYr4Rt { get; set; }
        public decimal? DepCompOrigYr4Rt { get; set; }
        public decimal? DepComp4yrTransYr4Rt { get; set; }
        public decimal? DepComp2yrTransYr4Rt { get; set; }
        public decimal? DepWdrawOrigYr4Rt { get; set; }
        public decimal? DepWdraw4yrTransYr4Rt { get; set; }
        public decimal? DepWdraw2yrTransYr4Rt { get; set; }
        public decimal? DepEnrlOrigYr4Rt { get; set; }
        public decimal? DepEnrl4yrTransYr4Rt { get; set; }
        public decimal? DepEnrl2yrTransYr4Rt { get; set; }
        public decimal? DepUnknOrigYr4Rt { get; set; }
        public decimal? DepUnkn4yrTransYr4Rt { get; set; }
        public decimal? DepUnkn2yrTransYr4Rt { get; set; }
        public decimal? IndDeathYr4Rt { get; set; }
        public decimal? IndCompOrigYr4Rt { get; set; }
        public decimal? IndComp4yrTransYr4Rt { get; set; }
        public decimal? IndComp2yrTransYr4Rt { get; set; }
        public decimal? IndWdrawOrigYr4Rt { get; set; }
        public decimal? IndWdraw4yrTransYr4Rt { get; set; }
        public decimal? IndWdraw2yrTransYr4Rt { get; set; }
        public decimal? IndEnrlOrigYr4Rt { get; set; }
        public decimal? IndEnrl4yrTransYr4Rt { get; set; }
        public decimal? IndEnrl2yrTransYr4Rt { get; set; }
        public decimal? IndUnknOrigYr4Rt { get; set; }
        public decimal? IndUnkn4yrTransYr4Rt { get; set; }
        public decimal? IndUnkn2yrTransYr4Rt { get; set; }
        public decimal? FemaleDeathYr4Rt { get; set; }
        public decimal? FemaleCompOrigYr4Rt { get; set; }
        public decimal? FemaleComp4yrTransYr4Rt { get; set; }
        public decimal? FemaleComp2yrTransYr4Rt { get; set; }
        public decimal? FemaleWdrawOrigYr4Rt { get; set; }
        public decimal? FemaleWdraw4yrTransYr4Rt { get; set; }
        public decimal? FemaleWdraw2yrTransYr4Rt { get; set; }
        public decimal? FemaleEnrlOrigYr4Rt { get; set; }
        public decimal? FemaleEnrl4yrTransYr4Rt { get; set; }
        public decimal? FemaleEnrl2yrTransYr4Rt { get; set; }
        public decimal? FemaleUnknOrigYr4Rt { get; set; }
        public decimal? FemaleUnkn4yrTransYr4Rt { get; set; }
        public decimal? FemaleUnkn2yrTransYr4Rt { get; set; }
        public decimal? MaleDeathYr4Rt { get; set; }
        public decimal? MaleCompOrigYr4Rt { get; set; }
        public decimal? MaleComp4yrTransYr4Rt { get; set; }
        public decimal? MaleComp2yrTransYr4Rt { get; set; }
        public decimal? MaleWdrawOrigYr4Rt { get; set; }
        public decimal? MaleWdraw4yrTransYr4Rt { get; set; }
        public decimal? MaleWdraw2yrTransYr4Rt { get; set; }
        public decimal? MaleEnrlOrigYr4Rt { get; set; }
        public decimal? MaleEnrl4yrTransYr4Rt { get; set; }
        public decimal? MaleEnrl2yrTransYr4Rt { get; set; }
        public decimal? MaleUnknOrigYr4Rt { get; set; }
        public decimal? MaleUnkn4yrTransYr4Rt { get; set; }
        public decimal? MaleUnkn2yrTransYr4Rt { get; set; }
        public decimal? PellDeathYr4Rt { get; set; }
        public decimal? PellCompOrigYr4Rt { get; set; }
        public decimal? PellComp4yrTransYr4Rt { get; set; }
        public decimal? PellComp2yrTransYr4Rt { get; set; }
        public decimal? PellWdrawOrigYr4Rt { get; set; }
        public decimal? PellWdraw4yrTransYr4Rt { get; set; }
        public decimal? PellWdraw2yrTransYr4Rt { get; set; }
        public decimal? PellEnrlOrigYr4Rt { get; set; }
        public decimal? PellEnrl4yrTransYr4Rt { get; set; }
        public decimal? PellEnrl2yrTransYr4Rt { get; set; }
        public decimal? PellUnknOrigYr4Rt { get; set; }
        public decimal? PellUnkn4yrTransYr4Rt { get; set; }
        public decimal? PellUnkn2yrTransYr4Rt { get; set; }
        public decimal? NopellDeathYr4Rt { get; set; }
        public decimal? NopellCompOrigYr4Rt { get; set; }
        public decimal? NopellComp4yrTransYr4Rt { get; set; }
        public decimal? NopellComp2yrTransYr4Rt { get; set; }
        public decimal? NopellWdrawOrigYr4Rt { get; set; }
        public decimal? NopellWdraw4yrTransYr4Rt { get; set; }
        public decimal? NopellWdraw2yrTransYr4Rt { get; set; }
        public decimal? NopellEnrlOrigYr4Rt { get; set; }
        public decimal? NopellEnrl4yrTransYr4Rt { get; set; }
        public decimal? NopellEnrl2yrTransYr4Rt { get; set; }
        public decimal? NopellUnknOrigYr4Rt { get; set; }
        public decimal? NopellUnkn4yrTransYr4Rt { get; set; }
        public decimal? NopellUnkn2yrTransYr4Rt { get; set; }
        public decimal? LoanDeathYr4Rt { get; set; }
        public decimal? LoanCompOrigYr4Rt { get; set; }
        public decimal? LoanComp4yrTransYr4Rt { get; set; }
        public decimal? LoanComp2yrTransYr4Rt { get; set; }
        public decimal? LoanWdrawOrigYr4Rt { get; set; }
        public decimal? LoanWdraw4yrTransYr4Rt { get; set; }
        public decimal? LoanWdraw2yrTransYr4Rt { get; set; }
        public decimal? LoanEnrlOrigYr4Rt { get; set; }
        public decimal? LoanEnrl4yrTransYr4Rt { get; set; }
        public decimal? LoanEnrl2yrTransYr4Rt { get; set; }
        public decimal? LoanUnknOrigYr4Rt { get; set; }
        public decimal? LoanUnkn4yrTransYr4Rt { get; set; }
        public decimal? LoanUnkn2yrTransYr4Rt { get; set; }
        public decimal? NoloanDeathYr4Rt { get; set; }
        public decimal? NoloanCompOrigYr4Rt { get; set; }
        public decimal? NoloanComp4yrTransYr4Rt { get; set; }
        public decimal? NoloanComp2yrTransYr4Rt { get; set; }
        public decimal? NoloanWdrawOrigYr4Rt { get; set; }
        public decimal? NoloanWdraw4yrTransYr4Rt { get; set; }
        public decimal? NoloanWdraw2yrTransYr4Rt { get; set; }
        public decimal? NoloanEnrlOrigYr4Rt { get; set; }
        public decimal? NoloanEnrl4yrTransYr4Rt { get; set; }
        public decimal? NoloanEnrl2yrTransYr4Rt { get; set; }
        public decimal? NoloanUnknOrigYr4Rt { get; set; }
        public decimal? NoloanUnkn4yrTransYr4Rt { get; set; }
        public decimal? NoloanUnkn2yrTransYr4Rt { get; set; }
        public decimal? FirstgenDeathYr4Rt { get; set; }
        public decimal? FirstgenCompOrigYr4Rt { get; set; }
        public decimal? FirstgenComp4yrTransYr4Rt { get; set; }
        public decimal? FirstgenComp2yrTransYr4Rt { get; set; }
        public decimal? FirstgenWdrawOrigYr4Rt { get; set; }
        public decimal? FirstgenWdraw4yrTransYr4Rt { get; set; }
        public decimal? FirstgenWdraw2yrTransYr4Rt { get; set; }
        public decimal? FirstgenEnrlOrigYr4Rt { get; set; }
        public decimal? FirstgenEnrl4yrTransYr4Rt { get; set; }
        public decimal? FirstgenEnrl2yrTransYr4Rt { get; set; }
        public decimal? FirstgenUnknOrigYr4Rt { get; set; }
        public decimal? FirstgenUnkn4yrTransYr4Rt { get; set; }
        public decimal? FirstgenUnkn2yrTransYr4Rt { get; set; }
        public decimal? Not1stgenDeathYr4Rt { get; set; }
        public decimal? Not1stgenCompOrigYr4Rt { get; set; }
        public decimal? Not1stgenComp4yrTransYr4Rt { get; set; }
        public decimal? Not1stgenComp2yrTransYr4Rt { get; set; }
        public decimal? Not1stgenWdrawOrigYr4Rt { get; set; }
        public decimal? Not1stgenWdraw4yrTransYr4Rt { get; set; }
        public decimal? Not1stgenWdraw2yrTransYr4Rt { get; set; }
        public decimal? Not1stgenEnrlOrigYr4Rt { get; set; }
        public decimal? Not1stgenEnrl4yrTransYr4Rt { get; set; }
        public decimal? Not1stgenEnrl2yrTransYr4Rt { get; set; }
        public decimal? Not1stgenUnknOrigYr4Rt { get; set; }
        public decimal? Not1stgenUnkn4yrTransYr4Rt { get; set; }
        public decimal? Not1stgenUnkn2yrTransYr4Rt { get; set; }
        public decimal? DeathYr6Rt { get; set; }
        public decimal? CompOrigYr6Rt { get; set; }
        public decimal? Comp4yrTransYr6Rt { get; set; }
        public decimal? Comp2yrTransYr6Rt { get; set; }
        public decimal? WdrawOrigYr6Rt { get; set; }
        public decimal? Wdraw4yrTransYr6Rt { get; set; }
        public decimal? Wdraw2yrTransYr6Rt { get; set; }
        public decimal? EnrlOrigYr6Rt { get; set; }
        public decimal? Enrl4yrTransYr6Rt { get; set; }
        public decimal? Enrl2yrTransYr6Rt { get; set; }
        public decimal? UnknOrigYr6Rt { get; set; }
        public decimal? Unkn4yrTransYr6Rt { get; set; }
        public decimal? Unkn2yrTransYr6Rt { get; set; }
        public decimal? LoIncDeathYr6Rt { get; set; }
        public decimal? LoIncCompOrigYr6Rt { get; set; }
        public decimal? LoIncComp4yrTransYr6Rt { get; set; }
        public decimal? LoIncComp2yrTransYr6Rt { get; set; }
        public decimal? LoIncWdrawOrigYr6Rt { get; set; }
        public decimal? LoIncWdraw4yrTransYr6Rt { get; set; }
        public decimal? LoIncWdraw2yrTransYr6Rt { get; set; }
        public decimal? LoIncEnrlOrigYr6Rt { get; set; }
        public decimal? LoIncEnrl4yrTransYr6Rt { get; set; }
        public decimal? LoIncEnrl2yrTransYr6Rt { get; set; }
        public decimal? LoIncUnknOrigYr6Rt { get; set; }
        public decimal? LoIncUnkn4yrTransYr6Rt { get; set; }
        public decimal? LoIncUnkn2yrTransYr6Rt { get; set; }
        public decimal? MdIncDeathYr6Rt { get; set; }
        public decimal? MdIncCompOrigYr6Rt { get; set; }
        public decimal? MdIncComp4yrTransYr6Rt { get; set; }
        public decimal? MdIncComp2yrTransYr6Rt { get; set; }
        public decimal? MdIncWdrawOrigYr6Rt { get; set; }
        public decimal? MdIncWdraw4yrTransYr6Rt { get; set; }
        public decimal? MdIncWdraw2yrTransYr6Rt { get; set; }
        public decimal? MdIncEnrlOrigYr6Rt { get; set; }
        public decimal? MdIncEnrl4yrTransYr6Rt { get; set; }
        public decimal? MdIncEnrl2yrTransYr6Rt { get; set; }
        public decimal? MdIncUnknOrigYr6Rt { get; set; }
        public decimal? MdIncUnkn4yrTransYr6Rt { get; set; }
        public decimal? MdIncUnkn2yrTransYr6Rt { get; set; }
        public decimal? HiIncDeathYr6Rt { get; set; }
        public decimal? HiIncCompOrigYr6Rt { get; set; }
        public decimal? HiIncComp4yrTransYr6Rt { get; set; }
        public decimal? HiIncComp2yrTransYr6Rt { get; set; }
        public decimal? HiIncWdrawOrigYr6Rt { get; set; }
        public decimal? HiIncWdraw4yrTransYr6Rt { get; set; }
        public decimal? HiIncWdraw2yrTransYr6Rt { get; set; }
        public decimal? HiIncEnrlOrigYr6Rt { get; set; }
        public decimal? HiIncEnrl4yrTransYr6Rt { get; set; }
        public decimal? HiIncEnrl2yrTransYr6Rt { get; set; }
        public decimal? HiIncUnknOrigYr6Rt { get; set; }
        public decimal? HiIncUnkn4yrTransYr6Rt { get; set; }
        public decimal? HiIncUnkn2yrTransYr6Rt { get; set; }
        public decimal? DepDeathYr6Rt { get; set; }
        public decimal? DepCompOrigYr6Rt { get; set; }
        public decimal? DepComp4yrTransYr6Rt { get; set; }
        public decimal? DepComp2yrTransYr6Rt { get; set; }
        public decimal? DepWdrawOrigYr6Rt { get; set; }
        public decimal? DepWdraw4yrTransYr6Rt { get; set; }
        public decimal? DepWdraw2yrTransYr6Rt { get; set; }
        public decimal? DepEnrlOrigYr6Rt { get; set; }
        public decimal? DepEnrl4yrTransYr6Rt { get; set; }
        public decimal? DepEnrl2yrTransYr6Rt { get; set; }
        public decimal? DepUnknOrigYr6Rt { get; set; }
        public decimal? DepUnkn4yrTransYr6Rt { get; set; }
        public decimal? DepUnkn2yrTransYr6Rt { get; set; }
        public decimal? IndDeathYr6Rt { get; set; }
        public decimal? IndCompOrigYr6Rt { get; set; }
        public decimal? IndComp4yrTransYr6Rt { get; set; }
        public decimal? IndComp2yrTransYr6Rt { get; set; }
        public decimal? IndWdrawOrigYr6Rt { get; set; }
        public decimal? IndWdraw4yrTransYr6Rt { get; set; }
        public decimal? IndWdraw2yrTransYr6Rt { get; set; }
        public decimal? IndEnrlOrigYr6Rt { get; set; }
        public decimal? IndEnrl4yrTransYr6Rt { get; set; }
        public decimal? IndEnrl2yrTransYr6Rt { get; set; }
        public decimal? IndUnknOrigYr6Rt { get; set; }
        public decimal? IndUnkn4yrTransYr6Rt { get; set; }
        public decimal? IndUnkn2yrTransYr6Rt { get; set; }
        public decimal? FemaleDeathYr6Rt { get; set; }
        public decimal? FemaleCompOrigYr6Rt { get; set; }
        public decimal? FemaleComp4yrTransYr6Rt { get; set; }
        public decimal? FemaleComp2yrTransYr6Rt { get; set; }
        public decimal? FemaleWdrawOrigYr6Rt { get; set; }
        public decimal? FemaleWdraw4yrTransYr6Rt { get; set; }
        public decimal? FemaleWdraw2yrTransYr6Rt { get; set; }
        public decimal? FemaleEnrlOrigYr6Rt { get; set; }
        public decimal? FemaleEnrl4yrTransYr6Rt { get; set; }
        public decimal? FemaleEnrl2yrTransYr6Rt { get; set; }
        public decimal? FemaleUnknOrigYr6Rt { get; set; }
        public decimal? FemaleUnkn4yrTransYr6Rt { get; set; }
        public decimal? FemaleUnkn2yrTransYr6Rt { get; set; }
        public decimal? MaleDeathYr6Rt { get; set; }
        public decimal? MaleCompOrigYr6Rt { get; set; }
        public decimal? MaleComp4yrTransYr6Rt { get; set; }
        public decimal? MaleComp2yrTransYr6Rt { get; set; }
        public decimal? MaleWdrawOrigYr6Rt { get; set; }
        public decimal? MaleWdraw4yrTransYr6Rt { get; set; }
        public decimal? MaleWdraw2yrTransYr6Rt { get; set; }
        public decimal? MaleEnrlOrigYr6Rt { get; set; }
        public decimal? MaleEnrl4yrTransYr6Rt { get; set; }
        public decimal? MaleEnrl2yrTransYr6Rt { get; set; }
        public decimal? MaleUnknOrigYr6Rt { get; set; }
        public decimal? MaleUnkn4yrTransYr6Rt { get; set; }
        public decimal? MaleUnkn2yrTransYr6Rt { get; set; }
        public decimal? PellDeathYr6Rt { get; set; }
        public decimal? PellCompOrigYr6Rt { get; set; }
        public decimal? PellComp4yrTransYr6Rt { get; set; }
        public decimal? PellComp2yrTransYr6Rt { get; set; }
        public decimal? PellWdrawOrigYr6Rt { get; set; }
        public decimal? PellWdraw4yrTransYr6Rt { get; set; }
        public decimal? PellWdraw2yrTransYr6Rt { get; set; }
        public decimal? PellEnrlOrigYr6Rt { get; set; }
        public decimal? PellEnrl4yrTransYr6Rt { get; set; }
        public decimal? PellEnrl2yrTransYr6Rt { get; set; }
        public decimal? PellUnknOrigYr6Rt { get; set; }
        public decimal? PellUnkn4yrTransYr6Rt { get; set; }
        public decimal? PellUnkn2yrTransYr6Rt { get; set; }
        public decimal? NopellDeathYr6Rt { get; set; }
        public decimal? NopellCompOrigYr6Rt { get; set; }
        public decimal? NopellComp4yrTransYr6Rt { get; set; }
        public decimal? NopellComp2yrTransYr6Rt { get; set; }
        public decimal? NopellWdrawOrigYr6Rt { get; set; }
        public decimal? NopellWdraw4yrTransYr6Rt { get; set; }
        public decimal? NopellWdraw2yrTransYr6Rt { get; set; }
        public decimal? NopellEnrlOrigYr6Rt { get; set; }
        public decimal? NopellEnrl4yrTransYr6Rt { get; set; }
        public decimal? NopellEnrl2yrTransYr6Rt { get; set; }
        public decimal? NopellUnknOrigYr6Rt { get; set; }
        public decimal? NopellUnkn4yrTransYr6Rt { get; set; }
        public decimal? NopellUnkn2yrTransYr6Rt { get; set; }
        public decimal? LoanDeathYr6Rt { get; set; }
        public decimal? LoanCompOrigYr6Rt { get; set; }
        public decimal? LoanComp4yrTransYr6Rt { get; set; }
        public decimal? LoanComp2yrTransYr6Rt { get; set; }
        public decimal? LoanWdrawOrigYr6Rt { get; set; }
        public decimal? LoanWdraw4yrTransYr6Rt { get; set; }
        public decimal? LoanWdraw2yrTransYr6Rt { get; set; }
        public decimal? LoanEnrlOrigYr6Rt { get; set; }
        public decimal? LoanEnrl4yrTransYr6Rt { get; set; }
        public decimal? LoanEnrl2yrTransYr6Rt { get; set; }
        public decimal? LoanUnknOrigYr6Rt { get; set; }
        public decimal? LoanUnkn4yrTransYr6Rt { get; set; }
        public decimal? LoanUnkn2yrTransYr6Rt { get; set; }
        public decimal? NoloanDeathYr6Rt { get; set; }
        public decimal? NoloanCompOrigYr6Rt { get; set; }
        public decimal? NoloanComp4yrTransYr6Rt { get; set; }
        public decimal? NoloanComp2yrTransYr6Rt { get; set; }
        public decimal? NoloanWdrawOrigYr6Rt { get; set; }
        public decimal? NoloanWdraw4yrTransYr6Rt { get; set; }
        public decimal? NoloanWdraw2yrTransYr6Rt { get; set; }
        public decimal? NoloanEnrlOrigYr6Rt { get; set; }
        public decimal? NoloanEnrl4yrTransYr6Rt { get; set; }
        public decimal? NoloanEnrl2yrTransYr6Rt { get; set; }
        public decimal? NoloanUnknOrigYr6Rt { get; set; }
        public decimal? NoloanUnkn4yrTransYr6Rt { get; set; }
        public decimal? NoloanUnkn2yrTransYr6Rt { get; set; }
        public decimal? FirstgenDeathYr6Rt { get; set; }
        public decimal? FirstgenCompOrigYr6Rt { get; set; }
        public decimal? FirstgenComp4yrTransYr6Rt { get; set; }
        public decimal? FirstgenComp2yrTransYr6Rt { get; set; }
        public decimal? FirstgenWdrawOrigYr6Rt { get; set; }
        public decimal? FirstgenWdraw4yrTransYr6Rt { get; set; }
        public decimal? FirstgenWdraw2yrTransYr6Rt { get; set; }
        public decimal? FirstgenEnrlOrigYr6Rt { get; set; }
        public decimal? FirstgenEnrl4yrTransYr6Rt { get; set; }
        public decimal? FirstgenEnrl2yrTransYr6Rt { get; set; }
        public decimal? FirstgenUnknOrigYr6Rt { get; set; }
        public decimal? FirstgenUnkn4yrTransYr6Rt { get; set; }
        public decimal? FirstgenUnkn2yrTransYr6Rt { get; set; }
        public decimal? Not1stgenDeathYr6Rt { get; set; }
        public decimal? Not1stgenCompOrigYr6Rt { get; set; }
        public decimal? Not1stgenComp4yrTransYr6Rt { get; set; }
        public decimal? Not1stgenComp2yrTransYr6Rt { get; set; }
        public decimal? Not1stgenWdrawOrigYr6Rt { get; set; }
        public decimal? Not1stgenWdraw4yrTransYr6Rt { get; set; }
        public decimal? Not1stgenWdraw2yrTransYr6Rt { get; set; }
        public decimal? Not1stgenEnrlOrigYr6Rt { get; set; }
        public decimal? Not1stgenEnrl4yrTransYr6Rt { get; set; }
        public decimal? Not1stgenEnrl2yrTransYr6Rt { get; set; }
        public decimal? Not1stgenUnknOrigYr6Rt { get; set; }
        public decimal? Not1stgenUnkn4yrTransYr6Rt { get; set; }
        public decimal? Not1stgenUnkn2yrTransYr6Rt { get; set; }
        public decimal? DeathYr8Rt { get; set; }
        public decimal? CompOrigYr8Rt { get; set; }
        public decimal? Comp4yrTransYr8Rt { get; set; }
        public decimal? Comp2yrTransYr8Rt { get; set; }
        public decimal? WdrawOrigYr8Rt { get; set; }
        public decimal? Wdraw4yrTransYr8Rt { get; set; }
        public decimal? Wdraw2yrTransYr8Rt { get; set; }
        public decimal? EnrlOrigYr8Rt { get; set; }
        public decimal? Enrl4yrTransYr8Rt { get; set; }
        public decimal? Enrl2yrTransYr8Rt { get; set; }
        public decimal? UnknOrigYr8Rt { get; set; }
        public decimal? Unkn4yrTransYr8Rt { get; set; }
        public decimal? Unkn2yrTransYr8Rt { get; set; }
        public decimal? LoIncDeathYr8Rt { get; set; }
        public decimal? LoIncCompOrigYr8Rt { get; set; }
        public decimal? LoIncComp4yrTransYr8Rt { get; set; }
        public decimal? LoIncComp2yrTransYr8Rt { get; set; }
        public decimal? LoIncWdrawOrigYr8Rt { get; set; }
        public decimal? LoIncWdraw4yrTransYr8Rt { get; set; }
        public decimal? LoIncWdraw2yrTransYr8Rt { get; set; }
        public decimal? LoIncEnrlOrigYr8Rt { get; set; }
        public decimal? LoIncEnrl4yrTransYr8Rt { get; set; }
        public decimal? LoIncEnrl2yrTransYr8Rt { get; set; }
        public decimal? LoIncUnknOrigYr8Rt { get; set; }
        public decimal? LoIncUnkn4yrTransYr8Rt { get; set; }
        public decimal? LoIncUnkn2yrTransYr8Rt { get; set; }
        public decimal? MdIncDeathYr8Rt { get; set; }
        public decimal? MdIncCompOrigYr8Rt { get; set; }
        public decimal? MdIncComp4yrTransYr8Rt { get; set; }
        public decimal? MdIncComp2yrTransYr8Rt { get; set; }
        public decimal? MdIncWdrawOrigYr8Rt { get; set; }
        public decimal? MdIncWdraw4yrTransYr8Rt { get; set; }
        public decimal? MdIncWdraw2yrTransYr8Rt { get; set; }
        public decimal? MdIncEnrlOrigYr8Rt { get; set; }
        public decimal? MdIncEnrl4yrTransYr8Rt { get; set; }
        public decimal? MdIncEnrl2yrTransYr8Rt { get; set; }
        public decimal? MdIncUnknOrigYr8Rt { get; set; }
        public decimal? MdIncUnkn4yrTransYr8Rt { get; set; }
        public decimal? MdIncUnkn2yrTransYr8Rt { get; set; }
        public decimal? HiIncDeathYr8Rt { get; set; }
        public decimal? HiIncCompOrigYr8Rt { get; set; }
        public decimal? HiIncComp4yrTransYr8Rt { get; set; }
        public decimal? HiIncComp2yrTransYr8Rt { get; set; }
        public decimal? HiIncWdrawOrigYr8Rt { get; set; }
        public decimal? HiIncWdraw4yrTransYr8Rt { get; set; }
        public decimal? HiIncWdraw2yrTransYr8Rt { get; set; }
        public decimal? HiIncEnrlOrigYr8Rt { get; set; }
        public decimal? HiIncEnrl4yrTransYr8Rt { get; set; }
        public decimal? HiIncEnrl2yrTransYr8Rt { get; set; }
        public decimal? HiIncUnknOrigYr8Rt { get; set; }
        public decimal? HiIncUnkn4yrTransYr8Rt { get; set; }
        public decimal? HiIncUnkn2yrTransYr8Rt { get; set; }
        public decimal? DepDeathYr8Rt { get; set; }
        public decimal? DepCompOrigYr8Rt { get; set; }
        public decimal? DepComp4yrTransYr8Rt { get; set; }
        public decimal? DepComp2yrTransYr8Rt { get; set; }
        public decimal? DepWdrawOrigYr8Rt { get; set; }
        public decimal? DepWdraw4yrTransYr8Rt { get; set; }
        public decimal? DepWdraw2yrTransYr8Rt { get; set; }
        public decimal? DepEnrlOrigYr8Rt { get; set; }
        public decimal? DepEnrl4yrTransYr8Rt { get; set; }
        public decimal? DepEnrl2yrTransYr8Rt { get; set; }
        public decimal? DepUnknOrigYr8Rt { get; set; }
        public decimal? DepUnkn4yrTransYr8Rt { get; set; }
        public decimal? DepUnkn2yrTransYr8Rt { get; set; }
        public decimal? IndDeathYr8Rt { get; set; }
        public decimal? IndCompOrigYr8Rt { get; set; }
        public decimal? IndComp4yrTransYr8Rt { get; set; }
        public decimal? IndComp2yrTransYr8Rt { get; set; }
        public decimal? IndWdrawOrigYr8Rt { get; set; }
        public decimal? IndWdraw4yrTransYr8Rt { get; set; }
        public decimal? IndWdraw2yrTransYr8Rt { get; set; }
        public decimal? IndEnrlOrigYr8Rt { get; set; }
        public decimal? IndEnrl4yrTransYr8Rt { get; set; }
        public decimal? IndEnrl2yrTransYr8Rt { get; set; }
        public decimal? IndUnknOrigYr8Rt { get; set; }
        public decimal? IndUnkn4yrTransYr8Rt { get; set; }
        public decimal? IndUnkn2yrTransYr8Rt { get; set; }
        public decimal? FemaleDeathYr8Rt { get; set; }
        public decimal? FemaleCompOrigYr8Rt { get; set; }
        public decimal? FemaleComp4yrTransYr8Rt { get; set; }
        public decimal? FemaleComp2yrTransYr8Rt { get; set; }
        public decimal? FemaleWdrawOrigYr8Rt { get; set; }
        public decimal? FemaleWdraw4yrTransYr8Rt { get; set; }
        public decimal? FemaleWdraw2yrTransYr8Rt { get; set; }
        public decimal? FemaleEnrlOrigYr8Rt { get; set; }
        public decimal? FemaleEnrl4yrTransYr8Rt { get; set; }
        public decimal? FemaleEnrl2yrTransYr8Rt { get; set; }
        public decimal? FemaleUnknOrigYr8Rt { get; set; }
        public decimal? FemaleUnkn4yrTransYr8Rt { get; set; }
        public decimal? FemaleUnkn2yrTransYr8Rt { get; set; }
        public decimal? MaleDeathYr8Rt { get; set; }
        public decimal? MaleCompOrigYr8Rt { get; set; }
        public decimal? MaleComp4yrTransYr8Rt { get; set; }
        public decimal? MaleComp2yrTransYr8Rt { get; set; }
        public decimal? MaleWdrawOrigYr8Rt { get; set; }
        public decimal? MaleWdraw4yrTransYr8Rt { get; set; }
        public decimal? MaleWdraw2yrTransYr8Rt { get; set; }
        public decimal? MaleEnrlOrigYr8Rt { get; set; }
        public decimal? MaleEnrl4yrTransYr8Rt { get; set; }
        public decimal? MaleEnrl2yrTransYr8Rt { get; set; }
        public decimal? MaleUnknOrigYr8Rt { get; set; }
        public decimal? MaleUnkn4yrTransYr8Rt { get; set; }
        public decimal? MaleUnkn2yrTransYr8Rt { get; set; }
        public decimal? PellDeathYr8Rt { get; set; }
        public decimal? PellCompOrigYr8Rt { get; set; }
        public decimal? PellComp4yrTransYr8Rt { get; set; }
        public decimal? PellComp2yrTransYr8Rt { get; set; }
        public decimal? PellWdrawOrigYr8Rt { get; set; }
        public decimal? PellWdraw4yrTransYr8Rt { get; set; }
        public decimal? PellWdraw2yrTransYr8Rt { get; set; }
        public decimal? PellEnrlOrigYr8Rt { get; set; }
        public decimal? PellEnrl4yrTransYr8Rt { get; set; }
        public decimal? PellEnrl2yrTransYr8Rt { get; set; }
        public decimal? PellUnknOrigYr8Rt { get; set; }
        public decimal? PellUnkn4yrTransYr8Rt { get; set; }
        public decimal? PellUnkn2yrTransYr8Rt { get; set; }
        public decimal? NopellDeathYr8Rt { get; set; }
        public decimal? NopellCompOrigYr8Rt { get; set; }
        public decimal? NopellComp4yrTransYr8Rt { get; set; }
        public decimal? NopellComp2yrTransYr8Rt { get; set; }
        public decimal? NopellWdrawOrigYr8Rt { get; set; }
        public decimal? NopellWdraw4yrTransYr8Rt { get; set; }
        public decimal? NopellWdraw2yrTransYr8Rt { get; set; }
        public decimal? NopellEnrlOrigYr8Rt { get; set; }
        public decimal? NopellEnrl4yrTransYr8Rt { get; set; }
        public decimal? NopellEnrl2yrTransYr8Rt { get; set; }
        public decimal? NopellUnknOrigYr8Rt { get; set; }
        public decimal? NopellUnkn4yrTransYr8Rt { get; set; }
        public decimal? NopellUnkn2yrTransYr8Rt { get; set; }
        public decimal? LoanDeathYr8Rt { get; set; }
        public decimal? LoanCompOrigYr8Rt { get; set; }
        public decimal? LoanComp4yrTransYr8Rt { get; set; }
        public decimal? LoanComp2yrTransYr8Rt { get; set; }
        public decimal? LoanWdrawOrigYr8Rt { get; set; }
        public decimal? LoanWdraw4yrTransYr8Rt { get; set; }
        public decimal? LoanWdraw2yrTransYr8Rt { get; set; }
        public decimal? LoanEnrlOrigYr8Rt { get; set; }
        public decimal? LoanEnrl4yrTransYr8Rt { get; set; }
        public decimal? LoanEnrl2yrTransYr8Rt { get; set; }
        public decimal? LoanUnknOrigYr8Rt { get; set; }
        public decimal? LoanUnkn4yrTransYr8Rt { get; set; }
        public decimal? LoanUnkn2yrTransYr8Rt { get; set; }
        public decimal? NoloanDeathYr8Rt { get; set; }
        public decimal? NoloanCompOrigYr8Rt { get; set; }
        public decimal? NoloanComp4yrTransYr8Rt { get; set; }
        public decimal? NoloanComp2yrTransYr8Rt { get; set; }
        public decimal? NoloanWdrawOrigYr8Rt { get; set; }
        public decimal? NoloanWdraw4yrTransYr8Rt { get; set; }
        public decimal? NoloanWdraw2yrTransYr8Rt { get; set; }
        public decimal? NoloanEnrlOrigYr8Rt { get; set; }
        public decimal? NoloanEnrl4yrTransYr8Rt { get; set; }
        public decimal? NoloanEnrl2yrTransYr8Rt { get; set; }
        public decimal? NoloanUnknOrigYr8Rt { get; set; }
        public decimal? NoloanUnkn4yrTransYr8Rt { get; set; }
        public decimal? NoloanUnkn2yrTransYr8Rt { get; set; }
        public decimal? FirstgenDeathYr8Rt { get; set; }
        public decimal? FirstgenCompOrigYr8Rt { get; set; }
        public decimal? FirstgenComp4yrTransYr8Rt { get; set; }
        public decimal? FirstgenComp2yrTransYr8Rt { get; set; }
        public decimal? FirstgenWdrawOrigYr8Rt { get; set; }
        public decimal? FirstgenWdraw4yrTransYr8Rt { get; set; }
        public decimal? FirstgenWdraw2yrTransYr8Rt { get; set; }
        public decimal? FirstgenEnrlOrigYr8Rt { get; set; }
        public decimal? FirstgenEnrl4yrTransYr8Rt { get; set; }
        public decimal? FirstgenEnrl2yrTransYr8Rt { get; set; }
        public decimal? FirstgenUnknOrigYr8Rt { get; set; }
        public decimal? FirstgenUnkn4yrTransYr8Rt { get; set; }
        public decimal? FirstgenUnkn2yrTransYr8Rt { get; set; }
        public decimal? Not1stgenDeathYr8Rt { get; set; }
        public decimal? Not1stgenCompOrigYr8Rt { get; set; }
        public decimal? Not1stgenComp4yrTransYr8Rt { get; set; }
        public decimal? Not1stgenComp2yrTransYr8Rt { get; set; }
        public decimal? Not1stgenWdrawOrigYr8Rt { get; set; }
        public decimal? Not1stgenWdraw4yrTransYr8Rt { get; set; }
        public decimal? Not1stgenWdraw2yrTransYr8Rt { get; set; }
        public decimal? Not1stgenEnrlOrigYr8Rt { get; set; }
        public decimal? Not1stgenEnrl4yrTransYr8Rt { get; set; }
        public decimal? Not1stgenEnrl2yrTransYr8Rt { get; set; }
        public decimal? Not1stgenUnknOrigYr8Rt { get; set; }
        public decimal? Not1stgenUnkn4yrTransYr8Rt { get; set; }
        public decimal? Not1stgenUnkn2yrTransYr8Rt { get; set; }

        public virtual Root Unit { get; set; }
    }
}
