using System;
using System.Collections.Generic;
using System.Text;

using TinyCsvParser.Mapping;
using TinyCsvParser.TypeConverter;

using JonasTest.Core;
using JonasTest.Parser.CSVConverters;

namespace JonasTest.Parser.CSVMapper
{
	public class CSVRepaymentMapper : CsvMapping<Repayment>
	{
		public CSVRepaymentMapper(List<string> headers)
			: base()
		{
			MapProperty(headers.IndexOf("UNITID"), x => x.UNITID);
			MapProperty(headers.IndexOf("CDR2"), x=>x.CDR2 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("CDR3"), x=>x.CDR3 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("RPY_1YR_RT"), x=>x.RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_1YR_RT"), x=>x.COMPL_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_1YR_RT"), x=>x.NONCOM_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_1YR_RT"), x=>x.LO_INC_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_1YR_RT"), x=>x.MD_INC_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_1YR_RT"), x=>x.HI_INC_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("DEP_RPY_1YR_RT"), x=>x.DEP_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("IND_RPY_1YR_RT"), x=>x.IND_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("PELL_RPY_1YR_RT"), x=>x.PELL_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_1YR_RT"), x=>x.NOPELL_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_1YR_RT"), x=>x.FEMALE_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MALE_RPY_1YR_RT"), x=>x.MALE_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_1YR_RT"), x=>x.FIRSTGEN_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_1YR_RT"), x=>x.NOTFIRSTGEN_RPY_1YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("RPY_3YR_RT"), x=>x.RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_3YR_RT"), x=>x.COMPL_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_3YR_RT"), x=>x.NONCOM_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_3YR_RT"), x=>x.LO_INC_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_3YR_RT"), x=>x.MD_INC_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_3YR_RT"), x=>x.HI_INC_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("DEP_RPY_3YR_RT"), x=>x.DEP_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("IND_RPY_3YR_RT"), x=>x.IND_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("PELL_RPY_3YR_RT"), x=>x.PELL_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_3YR_RT"), x=>x.NOPELL_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_3YR_RT"), x=>x.FEMALE_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MALE_RPY_3YR_RT"), x=>x.MALE_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_3YR_RT"), x=>x.FIRSTGEN_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_3YR_RT"), x=>x.NOTFIRSTGEN_RPY_3YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("RPY_5YR_RT"), x=>x.RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_5YR_RT"), x=>x.COMPL_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_5YR_RT"), x=>x.NONCOM_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_5YR_RT"), x=>x.LO_INC_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_5YR_RT"), x=>x.MD_INC_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_5YR_RT"), x=>x.HI_INC_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("DEP_RPY_5YR_RT"), x=>x.DEP_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("IND_RPY_5YR_RT"), x=>x.IND_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("PELL_RPY_5YR_RT"), x=>x.PELL_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_5YR_RT"), x=>x.NOPELL_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_5YR_RT"), x=>x.FEMALE_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MALE_RPY_5YR_RT"), x=>x.MALE_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_5YR_RT"), x=>x.FIRSTGEN_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_5YR_RT"), x=>x.NOTFIRSTGEN_RPY_5YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("RPY_7YR_RT"), x=>x.RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_7YR_RT"), x=>x.COMPL_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_7YR_RT"), x=>x.NONCOM_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_7YR_RT"), x=>x.LO_INC_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_7YR_RT"), x=>x.MD_INC_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_7YR_RT"), x=>x.HI_INC_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("DEP_RPY_7YR_RT"), x=>x.DEP_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("IND_RPY_7YR_RT"), x=>x.IND_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("PELL_RPY_7YR_RT"), x=>x.PELL_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_7YR_RT"), x=>x.NOPELL_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_7YR_RT"), x=>x.FEMALE_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MALE_RPY_7YR_RT"), x=>x.MALE_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_7YR_RT"), x=>x.FIRSTGEN_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_7YR_RT"), x=>x.NOTFIRSTGEN_RPY_7YR_RT 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("REPAY_DT_MDN"), x=>x.REPAY_DT_MDN );
		MapProperty(headers.IndexOf("REPAY_DT_N"), x=>x.REPAY_DT_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("RPY_1YR_N"), x=>x.RPY_1YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_1YR_N"), x=>x.COMPL_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_1YR_N"), x=>x.NONCOM_RPY_1YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_1YR_N"), x=>x.LO_INC_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_1YR_N"), x=>x.MD_INC_RPY_1YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_1YR_N"), x=>x.HI_INC_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("DEP_RPY_1YR_N"), x=>x.DEP_RPY_1YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("IND_RPY_1YR_N"), x=>x.IND_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("PELL_RPY_1YR_N"), x=>x.PELL_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_1YR_N"), x=>x.NOPELL_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_1YR_N"), x=>x.FEMALE_RPY_1YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MALE_RPY_1YR_N"), x=>x.MALE_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_1YR_N"), x=>x.FIRSTGEN_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_1YR_N"), x=>x.NOTFIRSTGEN_RPY_1YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("RPY_3YR_N"), x=>x.RPY_3YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_3YR_N"), x=>x.COMPL_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_3YR_N"), x=>x.NONCOM_RPY_3YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_3YR_N"), x=>x.LO_INC_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_3YR_N"), x=>x.MD_INC_RPY_3YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_3YR_N"), x=>x.HI_INC_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("DEP_RPY_3YR_N"), x=>x.DEP_RPY_3YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("IND_RPY_3YR_N"), x=>x.IND_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("PELL_RPY_3YR_N"), x=>x.PELL_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_3YR_N"), x=>x.NOPELL_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_3YR_N"), x=>x.FEMALE_RPY_3YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MALE_RPY_3YR_N"), x=>x.MALE_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_3YR_N"), x=>x.FIRSTGEN_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_3YR_N"), x=>x.NOTFIRSTGEN_RPY_3YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("RPY_5YR_N"), x=>x.RPY_5YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_5YR_N"), x=>x.COMPL_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_5YR_N"), x=>x.NONCOM_RPY_5YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_5YR_N"), x=>x.LO_INC_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_5YR_N"), x=>x.MD_INC_RPY_5YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_5YR_N"), x=>x.HI_INC_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("DEP_RPY_5YR_N"), x=>x.DEP_RPY_5YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("IND_RPY_5YR_N"), x=>x.IND_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("PELL_RPY_5YR_N"), x=>x.PELL_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_5YR_N"), x=>x.NOPELL_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_5YR_N"), x=>x.FEMALE_RPY_5YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MALE_RPY_5YR_N"), x=>x.MALE_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_5YR_N"), x=>x.FIRSTGEN_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_5YR_N"), x=>x.NOTFIRSTGEN_RPY_5YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("RPY_7YR_N"), x=>x.RPY_7YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_7YR_N"), x=>x.COMPL_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_7YR_N"), x=>x.NONCOM_RPY_7YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_7YR_N"), x=>x.LO_INC_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_7YR_N"), x=>x.MD_INC_RPY_7YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_7YR_N"), x=>x.HI_INC_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("DEP_RPY_7YR_N"), x=>x.DEP_RPY_7YR_N  							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("IND_RPY_7YR_N"), x=>x.IND_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("PELL_RPY_7YR_N"), x=>x.PELL_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_7YR_N"), x=>x.NOPELL_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_7YR_N"), x=>x.FEMALE_RPY_7YR_N   							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("MALE_RPY_7YR_N"), x=>x.MALE_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_7YR_N"), x=>x.FIRSTGEN_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_7YR_N"), x=>x.NOTFIRSTGEN_RPY_7YR_N 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("RPY_3YR_RT_SUPP"), x=>x.RPY_3YR_RT_SUPP    							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("LO_INC_RPY_3YR_RT_SUPP"), x=>x.LO_INC_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MD_INC_RPY_3YR_RT_SUPP"), x=>x.MD_INC_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("HI_INC_RPY_3YR_RT_SUPP"), x=>x.HI_INC_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("COMPL_RPY_3YR_RT_SUPP"), x=>x.COMPL_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NONCOM_RPY_3YR_RT_SUPP"), x=>x.NONCOM_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("DEP_RPY_3YR_RT_SUPP"), x=>x.DEP_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("IND_RPY_3YR_RT_SUPP"), x=>x.IND_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("PELL_RPY_3YR_RT_SUPP"), x=>x.PELL_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOPELL_RPY_3YR_RT_SUPP"), x=>x.NOPELL_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FEMALE_RPY_3YR_RT_SUPP"), x=>x.FEMALE_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("MALE_RPY_3YR_RT_SUPP"), x=>x.MALE_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("FIRSTGEN_RPY_3YR_RT_SUPP"), x=>x.FIRSTGEN_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("NOTFIRSTGEN_RPY_3YR_RT_SUPP"), x=>x.NOTFIRSTGEN_RPY_3YR_RT_SUPP 							, new SafeNullableDecimalConverter());
		MapProperty(headers.IndexOf("CDR2_DENOM"), x=>x.CDR2_DENOM 							, new SafeNullableIntegerConverter());
		MapProperty(headers.IndexOf("CDR3_DENOM"), x=>x.CDR3_DENOM, new SafeNullableIntegerConverter());
		}
	}
}